'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Analysis } from '@/lib/types';
import { formatDate } from '@/lib/data-service';
import { Badge, Button, DemoNotice, EmptyState, Icon, InsightPanel, Modal, SceneVisual } from './ui';
import { useWorkspace } from './workspace-provider';
export function AnalysisTable({rows,compact=false}:{rows:Analysis[];compact?:boolean}){
 const ws=useWorkspace();const router=useRouter();const [selected,setSelected]=useState<Analysis|null>(null);const [generating,setGenerating]=useState(false);
 function open(analysis:Analysis){ws.openAnalysis(analysis);setSelected(null);router.push(`${analysis.emergency?'/emergency':'/temporal'}?analysis=${analysis.id}`);}
 async function report(analysis:Analysis){setGenerating(true);try{await ws.generateReport(analysis);router.push('/reports');setSelected(null);}catch(e){ws.notify(e instanceof Error?e.message:'Report generation failed. Please try again.','error');}finally{setGenerating(false);}}
 if(!rows.length)return <EmptyState title="No analyses in this view" description="Adjust your filters or start an analysis to build this organization’s history." icon="layers"><Button variant="primary" icon="plus" onClick={ws.launchAnalysis}>New analysis</Button></EmptyState>;
 const location=selected?ws.data.locations.find(l=>l.id===selected.locationId)!:null;
 return <><div className="table-scroll"><table className={`analyses-table ${compact?'compact-table':''}`}><thead><tr><th>Analysis / location</th><th>Mission type</th><th>Created</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(a=>{const l=ws.data.locations.find(l=>l.id===a.locationId)!;return <tr key={a.id} onClick={e=>{if(!(e.target as HTMLElement).closest('button, a'))open(a);}}><td><button className="analysis-title-cell" aria-label={`Reopen ${a.title}`} onClick={()=>open(a)}><SceneVisual image={l.image} stage="during" category={a.category} className="table-thumbnail"/><span><strong>{a.title}</strong><small><Icon name="pin" size={13}/>{l.name}, {l.region}</small></span></button></td><td><span className="mission-type"><span className="mission-dot"/>{a.category==='Flooding'?'Flood analysis':a.category==='Water-body change'?'Water monitoring':a.category}</span></td><td className="table-date">{formatDate(a.date)}</td><td><Badge tone="green" dot>Completed</Badge></td><td><button className="table-open icon-button" title="Quick preview" aria-label={`Preview ${a.title}`} onClick={()=>setSelected(a)}><Icon name="eye" size={19}/></button></td></tr>;})}</tbody></table></div>
 {selected&&location&&<Modal wide title={selected.title} description={`${location.name}, ${location.region} · ${selected.id}`} onClose={()=>setSelected(null)}><DemoNotice/><div className="detail-stats"><div><span>Affected area</span><strong>{selected.area}<small>km²</small></strong></div><div><span>Change detected</span><strong>{selected.percentage}%</strong></div><div><span>Simulated confidence</span><strong>{selected.confidence}%</strong></div><div><span>Changed regions</span><strong>{selected.changeCount}</strong></div></div><div className="evidence-grid">{(['before','during','after'] as const).map(stage=><button className="evidence-card" key={stage} onClick={()=>open(selected)} aria-label={`Open ${stage} evidence in the analysis`}><SceneVisual image={location.image} stage={stage} category={selected.category}/><div><strong>{stage.toUpperCase()}</strong><span>{formatDate(selected[stage])}</span></div></button>)}</div><p className="image-caption">Illustrative basemap: Esri / Maxar. Observation dates, source metadata, and change masks are simulated.</p><InsightPanel insight={selected.insight}/><div className="modal-actions"><Button icon="map" onClick={()=>{ws.openAnalysis(selected);setSelected(null);router.push('/map');}}>View on map</Button><Button icon="layers" onClick={()=>open(selected)}>Reopen analysis</Button><Button variant="primary" icon="file" loading={generating} onClick={()=>report(selected)}>Generate report</Button></div></Modal>}</>;
}
