'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import type { Analysis, Change } from '@/lib/types';
import { formatDate } from '@/lib/data-service';
import { categoryMissions, datesForScene, emergencyMissions } from '@/lib/presentation';
import { useWorkspace } from './workspace-provider';
import { Badge, Button, DemoNotice, Icon, InsightPanel, PageHeader, SceneVisual, WorkflowNav } from './ui';
import { MapView } from './map-view';
const processingSteps=['Finding imagery','Comparing dates','Detecting changes','Classifying changes','Generating insight'];
const defaultDates={before:'2025-06-01',during:'2025-06-18',after:'2025-06-25'};
export function AnalysisWorkbench({mode}:{mode:'temporal'|'emergency'|'changes'}){
 const ws=useWorkspace();const router=useRouter();const params=useSearchParams();const requestedAnalysisId=params.get('analysis');const requestedSceneId=params.get('scene');const emergencyMode=mode==='emergency';
 const [event,setEvent]=useState(Object.keys(emergencyMissions).find(e=>emergencyMissions[e]===ws.mission)??'Flood');
 const [dates,setDates]=useState(ws.analysisDraft??defaultDates);const [view,setView]=useState('side');const [slider,setSlider]=useState(50);const [mask,setMask]=useState(true);const [stage,setStage]=useState('during');const [step,setStep]=useState(-1);const [result,setResult]=useState<Analysis|null>(null);const [selected,setSelected]=useState<Change|null>(null);const [error,setError]=useState('');const [reportLoading,setReportLoading]=useState(false);
 const runToken=useRef(0);const resultRef=useRef<HTMLDivElement>(null);const comparisonRef=useRef<HTMLElement>(null);const progressRef=useRef<HTMLElement>(null);
 const emergency=ws.data.emergencies.find(e=>e.type===event)??ws.data.emergencies[0];
 const missionCategory=Object.entries(categoryMissions).find(([,mission])=>mission===ws.mission)?.[0]??'Infrastructure damage';
 const category=result?.category??(emergencyMode?(['Flood','Cyclone','Severe Storm'].includes(event)?'Flooding':event==='Earthquake'?'Infrastructure damage':'Vegetation change'):missionCategory);
 const running=step>=0;const validDates=Object.values(dates).every(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d)));const dateOrderValid=validDates&&dates.before<dates.during&&dates.during<dates.after;
 const recoveryDate=Number.isFinite(Date.parse(dates.after))?new Date(Date.parse(dates.after)+7*86400000).toISOString().slice(0,10):'';
 const observationDate=stage==='recovery'?recoveryDate:dates[stage as keyof typeof dates];
 useEffect(()=>()=>{runToken.current+=1;},[]);
 useEffect(()=>{
  const id=requestedAnalysisId;
  const saved=id?ws.analyses.find(a=>a.id===id&&a.locationId===ws.location.id&&a.mission===ws.mission):undefined;
  runToken.current+=1;setStep(-1);setError('');
  if(saved){setResult(saved);setDates({before:saved.before,during:saved.during,after:saved.after});setSelected(saved.changes[0]);if(saved.emergency)setEvent(saved.event);}
  else{setResult(null);setSelected(null);}
 },[ws.organizationId,ws.location.id,ws.mission,requestedAnalysisId]);
 useEffect(()=>{
  if(requestedAnalysisId)return;
  const sceneId=requestedSceneId;
  const scene=ws.data.scenes.find(s=>s.id===sceneId)??ws.selectedScene;
  if(scene){const next=ws.selectedScene?.id===scene.id&&ws.analysisDraft?ws.analysisDraft:datesForScene(scene);setDates(next);ws.setAnalysisDraft(next);if(ws.selectedScene?.id!==scene.id)ws.selectScene(scene.id);}
 },[requestedSceneId]);
 useEffect(()=>{if(!emergencyMode)return;const selectedEvent=Object.keys(emergencyMissions).find(type=>emergencyMissions[type]===ws.mission);if(selectedEvent)setEvent(selectedEvent);else ws.setMission(emergencyMissions[event]);},[emergencyMode,ws.organizationId,ws.mission]);
 function selectEvent(type:string){setEvent(type);setResult(null);setSelected(null);ws.setMission(emergencyMissions[type]);const next=ws.data.emergencies.find(e=>e.type===type);if(next&&ws.location.id===emergency.locationId)ws.selectLocation(next.locationId);}
 function changeDate(key:keyof typeof dates,value:string){const next={...dates,[key]:value};setDates(next);ws.setAnalysisDraft(next);setResult(null);setError('');runToken.current+=1;setStep(-1);}
 function focusObservation(value:string){setStage(value);setView('focus');}
 async function runAnalysis(){
  if(!dateOrderValid){setError(validDates?'Choose dates in order: before, during, then after.':'Choose all three valid observation dates before running the analysis.');document.getElementById('analysis-config')?.scrollIntoView({behavior:'smooth',block:'center'});return;}
  const token=++runToken.current;setError('');setStep(0);setResult(null);setSelected(null);ws.setAnalysisDraft(dates);
  setTimeout(()=>progressRef.current?.scrollIntoView({behavior:'smooth',block:'center'}),100);
  try{
   const analysis=await ws.submitAnalysis({mission:emergencyMode?emergencyMissions[event]:ws.mission,locationId:ws.location.id,...dates,event:emergencyMode?event:'Land-cover change',emergency:emergencyMode,aoi:ws.aoi});
   for(let i=0;i<processingSteps.length;i++){if(token!==runToken.current)return;setStep(i);await new Promise(resolve=>setTimeout(resolve,450));}
   if(token!==runToken.current)return;setResult(analysis);setSelected(analysis.changes[0]);ws.addAnalysis(analysis);setStep(-1);ws.notify('Analysis complete. Review the mapped evidence and insight below.');setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),100);
  }catch(e){if(token!==runToken.current)return;setStep(-1);setError(e instanceof Error?e.message:'Analysis failed. Check your connection and try again.');}
 }
 async function generate(){if(!result)return;setReportLoading(true);try{await ws.generateReport(result);router.push('/reports');}catch(e){ws.notify(e instanceof Error?e.message:'Report generation failed. Please try again.','error');}finally{setReportLoading(false);}}
 function showEvidence(s:string){focusObservation(s);comparisonRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}
 return <div className={`analysis-workbench ${emergencyMode?'emergency-workbench':''}`}>
  <PageHeader eyebrow={emergencyMode?'OBSERVATION & IMPACT ASSESSMENT':'MULTI-TEMPORAL INTELLIGENCE'} title={emergencyMode?'Emergency analysis':mode==='changes'?'Change detection':'Temporal analysis'} description={emergencyMode?'Compare event stages, assess the impact, and keep recovery in view.':'Compare one area across multiple dates and understand what changed.'}>{result?<Button variant="primary" icon="file" loading={reportLoading} onClick={generate}>Generate report</Button>:<Button icon="file" onClick={()=>router.push('/reports')}>View reports</Button>}{emergencyMode&&<Badge tone="blue"><Icon name="shield-check" size={15}/>Observation, not prediction</Badge>}</PageHeader>
  <WorkflowNav current={mode} emergency={emergencyMode}/><DemoNotice/>
  {emergencyMode&&<div className="emergency-type-grid" role="radiogroup" aria-label="Disaster type">{ws.data.emergencies.map(e=><button role="radio" aria-checked={event===e.type} key={e.id} disabled={running} className={`emergency-type-card ${event===e.type?'selected':''}`} onClick={()=>selectEvent(e.type)}><span><Icon name={e.icon} size={24}/></span><strong>{e.type}</strong>{event===e.type&&<Icon name="check-circle" size={16}/>}</button>)}</div>}
  {mode==='changes'&&<div className="category-strip"><span>Change category</span>{ws.data.changes.map(c=><button className={ws.mission===categoryMissions[c.category]?'selected':''} aria-pressed={ws.mission===categoryMissions[c.category]} key={c.id} disabled={running} onClick={()=>ws.setMission(categoryMissions[c.category])}><span style={{background:c.color}}/>{c.category}</button>)}</div>}
  <section className="panel analysis-config" id="analysis-config"><div className="analysis-config-title"><span className="number-step">01</span><div><h2>Location & observation dates</h2><p>{emergencyMode?emergency.description:'Choose your mission, area of interest, and three dates to compare.'}</p></div><Badge tone="blue">{ws.organization.name}</Badge></div><div className={`analysis-config-fields ${emergencyMode?'emergency-fields':''}`}>{!emergencyMode&&<label>Mission<select aria-label="Analysis mission" disabled={running} value={ws.mission} onChange={e=>ws.setMission(e.target.value)}>{ws.missionOptions.map(m=><option key={m}>{m}</option>)}</select></label>}<label>Location / area of interest<select aria-label="Analysis location" disabled={running} value={ws.location.id} onChange={e=>ws.selectLocation(e.target.value)}>{ws.data.locations.map(l=><option key={l.id} value={l.id}>{l.name}, {l.region}</option>)}</select></label>{(['before','during','after'] as const).map((key,i)=><label key={key}><span className="date-stage-label"><span className={`stage-dot stage-dot-${i}`}/>{key==='before'?'Before':key==='during'?'During / observation':'After'}</span><input type="date" disabled={running} value={dates[key]} onChange={e=>changeDate(key,e.target.value)} aria-label={`${key} observation date`} aria-invalid={!!error&&!dateOrderValid}/></label>)}</div>{ws.selectedScene&&<div className="selected-scene-context"><Icon name="satellite" size={18}/><span>Selected scene<strong>{ws.selectedScene.title} · {formatDate(ws.selectedScene.date)}</strong></span><button className="text-button" disabled={running} onClick={()=>router.push('/map?tab=imagery')}>Change scene<Icon name="arrow-right" size={15}/></button></div>}{ws.aoi&&<div className="selected-aoi-note"><Icon name="aoi" size={17}/><span>Custom AOI: {ws.aoi.map(p=>p.map(v=>v.toFixed(3)).join(', ')).join(' → ')}. Demo statistics are illustrative, not recalculated for this selection.</span><button disabled={running} onClick={()=>ws.setAoi(undefined)}>Clear</button></div>}</section>
  <section className="panel comparison-panel" ref={comparisonRef} id="comparison"><div className="panel-heading"><div className="panel-title"><span className="number-step">02</span><h2>Compare observations</h2></div><div className="comparison-controls"><label className="mask-toggle"><input type="checkbox" checked={mask} onChange={e=>setMask(e.target.checked)}/><span/>Change mask</label><div className="segmented-control" aria-label="Comparison layout"><button aria-pressed={view==='side'} className={view==='side'?'selected':''} onClick={()=>setView('side')}><Icon name="grid" size={16}/>Side by side</button><button aria-pressed={view==='swipe'} className={view==='swipe'?'selected':''} onClick={()=>{setView('swipe');if(stage==='before')setStage('during');}}><Icon name="sliders" size={16}/>Swipe compare</button><button aria-pressed={view==='focus'} className={view==='focus'?'selected':''} onClick={()=>setView('focus')}><Icon name="eye" size={16}/>Single date</button></div></div></div>
   {view==='side'?<div className="comparison-scenes">{(['before','during','after'] as const).map((s,i)=><button className={`comparison-scene ${stage===s?'active':''}`} key={s} onClick={()=>focusObservation(s)} aria-label={`Inspect ${s} observation from ${formatDate(dates[s])}`}><div className="comparison-scene-top"><span><i className={`stage-dot stage-dot-${i}`}/>{s==='before'?'BEFORE':s==='during'?'DURING EVENT':'AFTER'}</span><span>{formatDate(dates[s])}</span></div><SceneVisual image={ws.location.image} stage={s} category={category} mask={mask}/><div className="comparison-scene-bottom"><span><Icon name="satellite" size={14}/>{s==='after'?'Landsat-9':'Sentinel-2'} · Demo</span><Icon name="expand" size={16}/></div></button>)}</div>:view==='focus'?<div className="observation-focus" key={stage}><SceneVisual image={ws.location.image} stage={stage} category={category} mask={mask}/><div className="focused-observation-label"><span>{stage==='recovery'?'RECOVERY':stage==='before'?'BEFORE EVENT':stage==='after'?'AFTER EVENT':'DURING EVENT'}</span><strong>{formatDate(observationDate)}</strong><small>{ws.location.name}, {ws.location.region} · Illustrative scene</small></div><span className="focused-observation-source"><Icon name="satellite" size={16}/>{stage==='after'||stage==='recovery'?'Landsat-9':'Sentinel-2'} · Simulated metadata</span></div>:<div className="swipe-comparison"><SceneVisual image={ws.location.image} stage="before" category={category} mask={false}/><div className="swipe-after" style={{clipPath:`inset(0 0 0 ${slider}%)`}}><SceneVisual image={ws.location.image} stage={stage} category={category} mask={mask}/></div><span className="swipe-label before">BEFORE · {formatDate(dates.before)}</span><span className="swipe-label after">{stage.toUpperCase()} · {formatDate(observationDate)}</span><div className="swipe-line" style={{left:`${slider}%`}}><span><Icon name="chevron-left" size={18}/><Icon name="chevron-right" size={18}/></span></div><input type="range" aria-label="Before and after image comparison" min="0" max="100" value={slider} onChange={e=>setSlider(Number(e.target.value))}/><span className="swipe-hint">Drag the divider or use the arrow keys to compare</span></div>}
   <div className="observation-timeline" aria-label="Observation timeline">{[{id:'before',label:'Before event',date:dates.before},{id:'during',label:'During event',date:dates.during},{id:'after',label:'After event',date:dates.after},{id:'recovery',label:'Recovery',date:recoveryDate}].map((item,i)=><button key={item.id} aria-pressed={stage===item.id} className={stage===item.id?'active':''} onClick={()=>focusObservation(item.id)}><span className="timeline-dot">{i===3?<Icon name="sprout" size={13}/>:null}</span><strong>{item.label}</strong><span>{formatDate(item.date,true)}</span></button>)}</div><div className="comparison-caption"><Icon name="info" size={16}/><span>Illustrative basemap with simulated dates and change overlays—not verified multi-date acquisitions.</span><span>© Esri / Maxar</span></div>
  </section>
  {stage==='recovery'&&<section className="recovery-banner"><span className="recovery-icon"><Icon name="sprout" size={24}/></span><div><h3>Recovery monitoring · prototype observation</h3><p>Illustrative follow-up: 62.1% of the demo impact footprint has receded. Remaining exposure requires independent verification.</p></div><Badge tone="green">7-day follow-up</Badge></section>}
  <div className="analysis-run-bar" id="analysis-run"><span className="run-bar-symbol"><Icon name="scan" size={28}/></span><div><h3>{emergencyMode?'Ready to assess the impact?':'Ready to see what changed?'}</h3><p>{emergencyMode?'Compare the event footprint and surface changes. No disaster predictions.':`Your results will be saved to ${ws.organization.name}.`}</p></div><Button variant="primary" icon="sparkles" loading={running} onClick={runAnalysis}>{running?'Analyzing observations…':'WHAT CHANGED HERE?'}</Button></div>
  {error&&<div className="error-banner" role="alert"><Icon name="alert" size={20}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><Icon name="x" size={18}/></button></div>}
  {running&&<section className="panel analysis-progress" ref={progressRef} aria-live="polite" aria-busy="true"><div className="small-section-title"><h3><Icon name="loader" className="spin" size={20}/>{processingSteps[step]}…</h3><button className="text-button" onClick={()=>{runToken.current+=1;setStep(-1);ws.notify('Analysis cancelled. Your dates and location are unchanged.','info');}}>Cancel analysis</button></div><div className="processing-steps">{processingSteps.map((s,i)=><div key={s} className={i<step?'complete':i===step?'current':''}><span>{i<step?<Icon name="check" size={19}/>:i===step?<Icon name="loader" className="spin" size={19}/>:i+1}</span><strong>{s}</strong></div>)}</div><div className="progress-track" role="progressbar" aria-label="Prototype analysis progress" aria-valuenow={(step+1)*20} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${((step+1)/5)*100}%`}}/></div><p>Running a deterministic prototype over the demo catalog. No operational model is being executed.</p></section>}
  {result&&<div ref={resultRef} className="analysis-results" id="analysis-results"><div className="results-heading"><div><span className="eyebrow"><Icon name="check-circle" size={16}/>ANALYSIS COMPLETE</span><h2>{emergencyMode?'Impact assessment':'Detected changes'}</h2><p>{ws.location.name}, {ws.location.region} · {result.id}</p></div><div><Badge tone="green" dot>Completed</Badge><Button variant="primary" icon="file" loading={reportLoading} onClick={generate}>Generate {emergencyMode?'emergency ':''}report</Button></div></div><div className="result-stats-grid">{[{icon:'aoi',label:'Affected area',value:ws.preferences.units==='ha'?(result.area*100).toLocaleString():result.area,unit:ws.preferences.units},{icon:'scan',label:'Change detected',value:result.percentage,unit:'%'},{icon:'target',label:'Simulated confidence',value:result.confidence,unit:'%'},{icon:'layers',label:'Changed regions',value:result.changeCount,unit:'regions'}].map(s=><button className="panel result-stat" key={s.label} onClick={()=>document.getElementById('result-map')?.scrollIntoView({behavior:'smooth',block:'center'})} aria-label={`${s.label}: ${s.value} ${s.unit}. View change evidence`}><span className="stat-icon"><Icon name={s.icon} size={20}/></span><span>{s.label}</span><strong>{s.value}<small>{s.unit}</small></strong></button>)}</div>
   {emergencyMode&&<div className="impact-breakdown panel">{[{icon:'waves',label:'Water expansion',value:`+${emergency.waterExpansion}%`,change:'flood'},{icon:'route',label:'Road segments exposed',value:emergency.roads,change:'damage'},{icon:'buildings',label:'Building footprints exposed',value:emergency.buildings,change:'damage'},{icon:'trees',label:'Vegetation affected',value:`${emergency.vegetation} km²`,change:'vegetation'}].map(s=><button key={s.label} onClick={()=>{setSelected(result.changes.find(c=>c.id===s.change)??result.changes[0]);document.getElementById('result-map')?.scrollIntoView({behavior:'smooth',block:'center'});}}><Icon name={s.icon}/><span>{s.label}</span><strong>{s.value}</strong></button>)}</div>}
   <div className="result-map-grid" id="result-map"><section className="panel"><div className="panel-heading"><div className="panel-title"><h2>{emergencyMode?'Impact map':'Detected change map'}</h2><Badge tone="blue">PROTOTYPE</Badge></div><Button variant="ghost" icon="maximize" onClick={()=>router.push(`/map${selected?`?change=${selected.id}`:''}`)}>Explore map</Button></div><MapView location={ws.location} changes={mask?result.changes:[]} focusChange={selected} onChangeSelect={setSelected} aoi={result.aoi}/><div className="map-panel-footer"><span><Icon name="crosshair" size={15}/>Select a region to inspect its evidence</span><span>{result.changes.length} demo categories</span></div></section><aside className="panel result-change-panel"><div className="panel-heading"><h2>Change breakdown</h2><span className="count-badge">{result.changes.length}</span></div><div className="change-list">{result.changes.map(c=><button className={`change-list-item ${selected?.id===c.id?'selected':''}`} aria-pressed={selected?.id===c.id} key={c.id} onClick={()=>setSelected(c)}><span className="change-color" style={{background:c.color}}/><div><strong>{c.category}</strong><span>{c.area} km² · {c.confidence}% confidence</span></div><Icon name="crosshair" size={17}/></button>)}</div>{selected&&<div className="change-evidence"><h3>Before / after evidence</h3><div className="mini-evidence">{['before','during'].map(s=><button key={s} onClick={()=>showEvidence(s)} aria-label={`Inspect ${s} evidence`}><SceneVisual image={ws.location.image} stage={s} category={selected.category}/><span>{s==='before'?'Before':'After change'}<Icon name="expand" size={13}/></span></button>)}</div><p>{selected.description}</p><div className="evidence-stat"><span>Percentage change</span><strong>{selected.percentage}%</strong></div><small className="subtle-text">Illustrative evidence · verify independently</small></div>}</aside></div>
   <InsightPanel insight={result.insight}/>{emergencyMode&&<section className="recovery-cta panel"><span className="recovery-icon"><Icon name="sprout" size={25}/></span><div><h3>Keep recovery in view.</h3><p>Review the follow-up observation and compare the simulated residual impact footprint.</p></div><Button icon="arrow-right" onClick={()=>showEvidence('recovery')}>Monitor recovery</Button></section>}
  </div>}
 </div>;
}
