'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { missionRoute } from '@/lib/presentation';
import { AnalysisTable } from './analysis-table';
import { MapView } from './map-view';
import { useWorkspace } from './workspace-provider';
import { Badge, Button, Icon, PageHeader } from './ui';

export function Dashboard(){
 const ws=useWorkspace();const router=useRouter();const [period,setPeriod]=useState('');const [dateMenu,setDateMenu]=useState(false);const [filter,setFilter]=useState(false);const [category,setCategory]=useState('');const dateRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!dateRef.current?.contains(e.target as Node))setDateMenu(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 const created=ws.analyses.filter(a=>!a.id.startsWith('AN-250'));const personal=!!ws.organization.typeId;
 const stats=[
  {label:'Satellite scenes',value:ws.organization.scenes.toLocaleString(),icon:'satellite',note:personal?'Available demo imagery':'Scenes in the demo catalog',href:'/search',points:'0,30 10,26 20,28 30,17 40,23 50,12 60,16 70,7 80,10 90,1'},
  {label:'Locations analyzed',value:(personal?new Set(ws.analyses.map(a=>a.locationId)).size:ws.organization.locations+new Set(created.map(a=>a.locationId)).size).toString().padStart(2,'0'),icon:'pin',note:'Explore your saved locations',href:'/saved',points:'0,30 14,29 22,23 36,23 44,16 55,20 68,12 77,13 90,3'},
  {label:'Changes detected',value:(ws.organization.changes+created.reduce((n,a)=>n+a.changeCount,0)).toString(),icon:'scan',note:'Review prototype detections',href:'/changes',points:'0,31 10,21 20,25 31,16 40,18 50,8 60,15 71,7 81,9 90,1'},
  {label:personal?'Emergency analyses':'Active emergencies',value:(ws.organization.emergencies+created.filter(a=>a.emergency).length).toString().padStart(2,'0'),icon:'shield',note:'Open impact assessment',href:'/emergency',points:''},
 ];
 const rows=ws.analyses.filter(a=>(!period||a.during.startsWith(period))&&(!category||a.category===category)).slice(0,4);
 const focusAnalysis=ws.analyses.find(a=>ws.organizationType==='disaster'?a.emergency:true);const focusLocation=ws.data.locations.find(l=>l.id===focusAnalysis?.locationId)??ws.location;
 function openFocus(){if(focusAnalysis){ws.openAnalysis(focusAnalysis);router.push(`${focusAnalysis.emergency?'/emergency':'/temporal'}?analysis=${focusAnalysis.id}`);}else ws.launchAnalysis();}
 return <div className="dashboard-page"><PageHeader eyebrow="DASHBOARD" title="Workspace overview" description="Your imagery, mission activity, and changing areas of interest—all in one place."><div className="date-filter-wrap" ref={dateRef}><Button icon="calendar" onClick={()=>setDateMenu(!dateMenu)} aria-expanded={dateMenu} onKeyDown={e=>{if(e.key==='Escape')setDateMenu(false);}}>{period==='2025-06'?'June 2025':period==='2025-05'?'May 2025':'All observation dates'}<Icon name="chevron" size={15}/></Button>{dateMenu&&<div className="date-popover">{[{id:'',label:'All observation dates'},{id:'2025-06',label:'June 2025 · demo period'},{id:'2025-05',label:'May 2025'}].map(p=><button key={p.id} onClick={()=>{setPeriod(p.id);setDateMenu(false);}} aria-pressed={period===p.id}>{p.label}{period===p.id&&<Icon name="check" size={16}/>}</button>)}<p>Applies to the recent analyses below.</p></div>}</div><Button variant="primary" icon="plus" onClick={ws.launchAnalysis}>New analysis</Button></PageHeader>
 <div className="workspace-context"><Link href="/organizations"><Icon name={ws.organization.icon} size={15}/>{ws.organization.name}</Link><Icon name="chevron-right" size={13}/><Link href="/missions">{ws.mission}<Icon name="chevron" size={13}/></Link><span className="context-demo">DEMO DATA</span></div>
 <div className="stats-grid">{stats.map((stat,i)=><Link href={stat.href} key={stat.label} className="stat-card" aria-label={`${stat.label}: ${stat.value}. ${stat.note}`}><div className="stat-top"><span>{stat.label}</span><span className="stat-icon"><Icon name={stat.icon} size={20}/></span></div><div className="stat-value-row"><strong>{stat.value}</strong>{stat.points?<svg className={`sparkline sparkline-${i}`} viewBox="0 0 92 38" aria-hidden="true"><polyline points={stat.points} fill="none" stroke="#8aa9d2" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>:<span className="stat-emergency-symbol"><Icon name="shield-check" size={33}/></span>}</div><div className="stat-bottom"><span>{stat.note}</span><Icon name="arrow-up-right" size={14}/></div></Link>)}</div>
 <div className="overview-grid"><section className="panel overview-map-panel"><div className="panel-heading"><div className="panel-title"><h2>Geospatial overview</h2><Badge tone="blue">3 change layers</Badge></div><div className="map-heading-actions"><select aria-label="Select monitored location" value={ws.location.id} onChange={e=>ws.selectLocation(e.target.value)}>{ws.data.locations.map(l=><option key={l.id} value={l.id}>{l.name}, {l.region}</option>)}</select><Link href="/map" className="icon-button" aria-label="Open map explorer" title="Open map explorer"><Icon name="maximize" size={18}/></Link></div></div><MapView location={ws.location} onLocationChange={ws.selectLocation} onChangeSelect={change=>router.push(`/map?change=${change.id}`)}/><div className="map-panel-footer"><span><Icon name="info" size={15}/>Illustrative basemap · Simulated change layers</span><Link href="/map">Open map explorer<Icon name="arrow-up-right" size={15}/></Link></div></section>
 <div className="overview-aside"><section className="panel quick-actions"><div className="panel-heading"><h2>Start exploring</h2><Icon name="zap" size={18}/></div><div className="quick-action-list">{[{href:'/search',icon:'search',title:'Find satellite imagery',text:'Search in your own words'},{href:'/temporal',icon:'layers',title:'Compare observation dates',text:'See your location across time'},{href:'/emergency',icon:'shield',title:'Assess an emergency',text:'Observe impact and recovery'}].map(action=><Link key={action.href} href={action.href} className="quick-action"><span className="quick-action-icon"><Icon name={action.icon} size={20}/></span><div><strong>{action.title}</strong><span>{action.text}</span></div><Icon name="chevron-right" size={17}/></Link>)}</div><button className="what-changed-button" onClick={()=>router.push('/changes')}><Icon name="sparkles" size={19}/><span>What changed here?</span><Icon name="arrow-right" size={18}/></button></section>
 <button className="emergency-spotlight" onClick={openFocus} aria-label={focusAnalysis?`Open ${focusAnalysis.title}`:'Start your first analysis'}><div className="emergency-spotlight-top"><span>{focusAnalysis?.emergency?'EMERGENCY FOCUS':'MISSION IN FOCUS'}</span><Badge>{focusAnalysis?'DEMO':'GET STARTED'}</Badge></div><div className="emergency-spotlight-main"><span className="flood-icon"><Icon name={focusAnalysis?.emergency?'waves':ws.organization.icon} size={23}/></span><div><h3>{focusAnalysis?.title??'Your first observation starts here'}</h3><p><Icon name="pin" size={14}/>{focusLocation.name}, {focusLocation.region}</p></div></div><div className="emergency-spotlight-bottom"><div>{focusAnalysis?<><strong>{focusAnalysis.area}<span>km² affected</span></strong><Badge tone="green" dot>Completed</Badge></>:<span>Configure {ws.mission}</span>}</div><Icon name="arrow-up-right" size={20}/></div></button></div></div>
 <section className="panel recent-analyses"><div className="panel-heading"><div className="panel-title"><h2>Recent analyses</h2><span className="count-badge">{ws.analyses.length}</span></div><div className="recent-heading-actions">{filter&&<select aria-label="Filter recent analyses by category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{Array.from(new Set(ws.analyses.map(a=>a.category))).map(c=><option key={c}>{c}</option>)}</select>}<button className={`filter-button ${filter?'active':''}`} onClick={()=>{setFilter(!filter);if(filter)setCategory('');}} aria-expanded={filter}><Icon name="sliders" size={16}/>Filter</button><Link href="/history">View all<Icon name="arrow-right" size={16}/></Link></div></div><AnalysisTable rows={rows} compact/></section>
 <div className="dashboard-bottom-line"><span><Icon name="shield-check" size={16}/>Evidence first. All findings are clearly labeled prototype data.</span><Link href={missionRoute(ws.mission)}>Continue your mission<Icon name="arrow-right" size={15}/></Link></div>
 </div>;
}
