'use client';
import { useEffect, useRef, useState } from 'react';
import { MapContainer, Marker, Polygon, Popup, Rectangle, ScaleControl, TileLayer, useMap, useMapEvents } from 'react-leaflet';
import { divIcon, type LatLngBoundsExpression, type Map as LeafletMapType } from 'leaflet';
import type { Change } from '@/lib/types';
import type { MapViewProps } from './map-view';
import { Icon } from './ui';
import { useWorkspace } from './workspace-provider';
import { satelliteBackgroundImage } from '@/lib/satellite-assets';

function MapController({lat,lng,focus,selecting,onPoint}:{lat:number;lng:number;focus?:Change|null;selecting:boolean;onPoint:(point:[number,number])=>void}){
 const map=useMap();
 useEffect(()=>{map.flyTo([lat,lng],12,{duration:.45,animate:!window.matchMedia('(prefers-reduced-motion: reduce)').matches});},[lat,lng,map]);
 useEffect(()=>{if(focus)map.flyTo([lat+focus.offset[0],lng+focus.offset[1]],14,{duration:.45,animate:!window.matchMedia('(prefers-reduced-motion: reduce)').matches});},[focus,lat,lng,map]);
 useEffect(()=>{const resize=new ResizeObserver(()=>map.invalidateSize());resize.observe(map.getContainer());return()=>resize.disconnect();},[map]);
 useMapEvents({click:e=>{if(selecting)onPoint([e.latlng.lat,e.latlng.lng]);}});return null;
}
function polygonFor(lat:number,lng:number,change:Change,scale:number):[number,number][]{const y=lat+change.offset[0],x=lng+change.offset[1];return [[y-.007*scale,x-.010*scale],[y+.002*scale,x-.013*scale],[y+.009*scale,x-.006*scale],[y+.012*scale,x+.003*scale],[y+.005*scale,x+.009*scale],[y-.003*scale,x+.007*scale],[y-.008*scale,x+.002*scale]];}
function markerIcon(color:string,icon='pin'){return divIcon({className:'satellite-marker',html:`<div class="map-marker-core" style="--pin-color:${color}"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.8">${icon==='waves'?'<path d="M2 8c3-4 5 4 9 0s6 4 11 0M2 13c3-4 5 4 9 0s6 4 11 0M2 18c3-4 5 4 9 0s6 4 11 0"/>':'<path d="M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12Z"/><circle cx="12" cy="9" r="2.5"/>'}</svg></div>`,iconSize:[39,46],iconAnchor:[19,42]});}
export default function LeafletMap({location,changes,onLocationChange,onChangeSelect,focusChange,onAreaChange,aoi,className='',expanded=false,observationStage,onStageChange}:MapViewProps){
 const ws=useWorkspace();const mapRef=useRef<LeafletMapType|null>(null);const wrapper=useRef<HTMLDivElement>(null);const searchRef=useRef<HTMLDivElement>(null);const layersRef=useRef<HTMLDivElement>(null);
 const [layer,setLayer]=useState<'satellite'|'map'>(ws.preferences.defaultLayer);const [layersOpen,setLayersOpen]=useState(false);const [query,setQuery]=useState('');const [searchOpen,setSearchOpen]=useState(false);const [selecting,setSelecting]=useState(false);const [firstPoint,setFirstPoint]=useState<[number,number]|null>(null);const [localAoi,setLocalAoi]=useState<[number,number][]|undefined>(aoi);const [hidden,setHidden]=useState<string[]>([]);const [localStage,setLocalStage]=useState(observationStage??'during');const [tileError,setTileError]=useState(false);const [tileReady,setTileReady]=useState(false);const [tileRetry,setTileRetry]=useState(0);const [fallbackFullscreen,setFallbackFullscreen]=useState(false);const [custom,setCustom]=useState<{lat:number;lng:number}|null>(null);
 const stage=observationStage??localStage;function setStage(value:string){setLocalStage(value);onStageChange?.(value);}
 useEffect(()=>{setCustom(null);setTileError(false);setFirstPoint(null);setSelecting(false);setQuery('');},[location.id]);
 useEffect(()=>{setLocalAoi(aoi);},[aoi]);
 useEffect(()=>{setTileError(false);setTileReady(false);},[layer,tileRetry]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!searchRef.current?.contains(e.target as Node))setSearchOpen(false);};const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSearchOpen(false);setLayersOpen(false);setSelecting(false);setFirstPoint(null);setFallbackFullscreen(false);}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',keys);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',keys);};},[]);
 const center=custom??location;const mapChanges=changes??(ws.organizationType==='environment'?ws.data.changes.filter(c=>['forest','vegetation','road'].includes(c.id)):ws.data.changes.slice(0,3));
 const matches=ws.data.locations.filter(l=>`${l.name} ${l.region} ${l.country}`.toLowerCase().includes(query.toLowerCase()));
 function searchCoordinates(){const pair=query.trim().match(/^(-?\d+(?:\.\d+)?)\s*[, ]\s*(-?\d+(?:\.\d+)?)$/);if(pair){const lat=Number(pair[1]),lng=Number(pair[2]);if(Math.abs(lat)<=85&&Math.abs(lng)<=180){setCustom({lat,lng});setSearchOpen(false);ws.notify('Coordinates located. Draw an area of interest to include it in your analysis.','info');return;}ws.notify('Enter latitude between −85 and 85, and longitude between −180 and 180.','error');return;}if(matches.length){onLocationChange?.(matches[0]);setSearchOpen(false);setQuery('');}else ws.notify('No matching location. Enter a catalog name or coordinates such as 9.97, 76.29.','info');}
 async function fullscreen(){try{if(fallbackFullscreen){setFallbackFullscreen(false);return;}if(document.fullscreenElement)await document.exitFullscreen();else await wrapper.current?.requestFullscreen();}catch{setFallbackFullscreen(true);}}
 function pointPicked(point:[number,number]){if(!firstPoint){setFirstPoint(point);return;}const bounds:[number,number][]=[[Math.min(firstPoint[0],point[0]),Math.min(firstPoint[1],point[1])],[Math.max(firstPoint[0],point[0]),Math.max(firstPoint[1],point[1])]];if(bounds[0][0]===bounds[1][0]||bounds[0][1]===bounds[1][1]){ws.notify('Select two different corners to define an area.','info');return;}setLocalAoi(bounds);onAreaChange?.(bounds);setFirstPoint(null);setSelecting(false);ws.notify('Area selected and saved to your analysis context.');}
 function toggleLayer(id:string){setHidden(previous=>previous.includes(id)?previous.filter(c=>c!==id):[...previous,id]);}
 function inspect(change:Change){onChangeSelect?.(change);mapRef.current?.flyTo([center.lat+change.offset[0],center.lng+change.offset[1]],14,{duration:.45});}
 return <div ref={wrapper} className={`map-workspace ${expanded?'map-expanded':''} ${selecting?'map-selecting':''} ${fallbackFullscreen?'map-page-fullscreen':''} ${className}`}>
  <MapContainer ref={mapRef} center={[center.lat,center.lng]} zoom={12} zoomControl={false} scrollWheelZoom={expanded} attributionControl style={{height:'100%',width:'100%',backgroundImage:satelliteBackgroundImage(location.image),backgroundSize:'cover',backgroundPosition:'center'}}>
   <TileLayer key={`${layer}-${tileRetry}`} url={layer==='satellite'?'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}':'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'} attribution={layer==='satellite'?'Tiles &copy; Esri — Esri, Maxar, Earthstar Geographics':'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'} maxZoom={18} eventHandlers={{tileerror:()=>setTileError(true),tileload:()=>setTileReady(true)}}/>
   <MapController lat={center.lat} lng={center.lng} focus={focusChange} selecting={selecting} onPoint={pointPicked}/>
   {stage!=='before'&&mapChanges.filter(c=>!hidden.includes(c.id)).map((change,i)=><Polygon key={change.id} positions={polygonFor(center.lat,center.lng,change,stage==='after'||stage==='recovery'?.65:1)} pathOptions={{color:change.color,fillColor:change.color,weight:2,fillOpacity:.2,dashArray:'5 4'}} eventHandlers={{click:()=>inspect(change)}}><Popup><div className="change-popup"><span className="eyebrow">DEMO REGION {i+1}</span><h3>{change.category}</h3><p>{change.area} km² · {change.confidence}% confidence</p><span>Simulated detection. Requires verification.</span><button onClick={()=>inspect(change)}>Inspect evidence<Icon name="arrow-right" size={15}/></button></div></Popup></Polygon>)}
   {stage!=='before'&&mapChanges.filter(c=>!hidden.includes(c.id)).map(change=><Marker key={`m-${change.id}`} title={`${change.category} · ${location.name}`} alt={`Inspect ${change.category} at ${location.name}`} position={[center.lat+change.offset[0],center.lng+change.offset[1]]} icon={markerIcon(change.color,change.id==='flood'?'waves':'pin')} eventHandlers={{click:()=>onChangeSelect?.(change)}}><Popup><div className="change-popup"><h3>{change.category}</h3><p>{location.name} · {change.area} km²</p><span>DEMO DATA · {change.confidence}% simulated confidence</span><button onClick={()=>inspect(change)}>View evidence<Icon name="arrow-right" size={15}/></button></div></Popup></Marker>)}
   {custom&&<Marker position={[custom.lat,custom.lng]} icon={markerIcon('#2563eb')} title="Searched coordinates" alt="Searched coordinates"><Popup><div className="change-popup"><h3>Coordinate reference</h3><p>{custom.lat.toFixed(4)}°, {custom.lng.toFixed(4)}°</p><span>Draw an AOI to use these coordinates in your next analysis.</span><button onClick={()=>{setSelecting(true);setFirstPoint(null);mapRef.current?.closePopup();}}>Select area<Icon name="aoi" size={16}/></button></div></Popup></Marker>}
   {localAoi&&localAoi.length===2&&<Rectangle bounds={localAoi as LatLngBoundsExpression} pathOptions={{color:'#78b4ff',weight:2,dashArray:'6 4',fillOpacity:.08}}/>}
   {firstPoint&&<Marker position={firstPoint} icon={markerIcon('#2563eb')} title="First corner of selected area"/>}<ScaleControl position="bottomright" imperial={false}/>
  </MapContainer>
  {onLocationChange&&<div ref={searchRef} className="map-top-left"><div className="map-search"><Icon name="search" size={18}/><input aria-label="Search map location or coordinates" aria-expanded={searchOpen} aria-controls="map-search-results" placeholder="Location or coordinates" value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true);}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();searchCoordinates();}if(e.key==='Escape')setSearchOpen(false);}}/>{query?<button onClick={()=>{setQuery('');setSearchOpen(false);}} aria-label="Clear location search"><Icon name="x" size={16}/></button>:<Icon name="chevron" size={14}/>}</div>{searchOpen&&<div className="map-search-results" id="map-search-results">{matches.length?matches.slice(0,5).map(l=><button key={l.id} onClick={()=>{onLocationChange(l);setQuery('');setSearchOpen(false);}}><Icon name="pin" size={16}/><span><strong>{l.name}</strong><small>{l.region}, {l.country}</small></span><Icon name="arrow-up-right" size={14}/></button>):<button onClick={searchCoordinates}><Icon name="crosshair" size={17}/><span>Go to coordinates<small>Example: 9.97, 76.29</small></span></button>}</div>}</div>}
  <div className="map-layer-switch" aria-label="Basemap"><button className={layer==='satellite'?'selected':''} aria-pressed={layer==='satellite'} onClick={()=>setLayer('satellite')}><Icon name="satellite" size={16}/>Satellite</button><button className={layer==='map'?'selected':''} aria-pressed={layer==='map'} onClick={()=>setLayer('map')}>Map</button></div>
  <div className="map-controls"><button title="Map layers" aria-label="Map layers" aria-expanded={layersOpen} className={layersOpen?'active':''} onClick={()=>setLayersOpen(!layersOpen)}><Icon name="layers" size={20}/></button><span/><button aria-label="Zoom in" title="Zoom in" onClick={()=>mapRef.current?.zoomIn()}><Icon name="plus" size={22}/></button><button aria-label="Zoom out" title="Zoom out" onClick={()=>mapRef.current?.zoomOut()}><Icon name="minus" size={22}/></button><span/><button aria-label="Center on location" title="Center on location" onClick={()=>mapRef.current?.flyTo([center.lat,center.lng],12,{duration:.45})}><Icon name="locate" size={20}/></button>{expanded&&<button title="Draw area of interest" aria-label="Draw area of interest" aria-pressed={selecting} className={selecting?'active':''} onClick={()=>{setSelecting(!selecting);setFirstPoint(null);setSearchOpen(false);setLayersOpen(false);}}><Icon name="aoi" size={20}/></button>}<button aria-label="Toggle fullscreen map" title="Toggle fullscreen" onClick={fullscreen}><Icon name="maximize" size={19}/></button></div>
  {layersOpen&&<div className="map-layers-panel" ref={layersRef}><h4>Map layers<button onClick={()=>setLayersOpen(false)} aria-label="Close map layers"><Icon name="x" size={18}/></button></h4><span className="mini-label">SIMULATED CHANGES</span>{mapChanges.map(c=><label key={c.id}><input type="checkbox" checked={!hidden.includes(c.id)} onChange={()=>toggleLayer(c.id)}/><span style={{background:c.color}}/>{c.category}</label>)}{!mapChanges.length&&<p>Enable the change mask to show detected regions.</p>}<span className="mini-label">OBSERVATION STAGE</span><div className="segmented-control">{['before','during','after'].map(s=><button key={s} className={stage===s?'selected':''} aria-pressed={stage===s} onClick={()=>setStage(s)}>{s}</button>)}</div><p>The basemap is illustrative. Dates and change layers are simulated.</p></div>}
  {selecting&&<div className="draw-instructions" role="status"><Icon name="aoi" size={18}/><span>{firstPoint?'Select the opposite corner to finish.':'Select two opposite corners of your area.'}</span><button onClick={()=>{setSelecting(false);setFirstPoint(null);}} aria-label="Cancel area selection"><Icon name="x" size={17}/></button></div>}
  <div className="map-location-card"><span className="map-location-icon"><Icon name="pin" size={20}/></span><div><strong>{custom?'Coordinate reference':`${location.name}, ${location.region}`}</strong><span>{Math.abs(center.lat).toFixed(4)}° {center.lat>=0?'N':'S'}<i/>{Math.abs(center.lng).toFixed(4)}° {center.lng>=0?'E':'W'}</span></div><span className="map-reference-label">{stage==='before'?'Before':stage==='after'?'After':stage==='recovery'?'Recovery':'Observation'}</span></div>
  <div className="map-legend" aria-label="Toggle change layers">{mapChanges.slice(0,3).map(c=><button key={c.id} className={hidden.includes(c.id)?'layer-hidden':''} aria-pressed={!hidden.includes(c.id)} title={`Toggle ${c.category} layer`} onClick={()=>toggleLayer(c.id)}><i style={{background:c.color}}/>{c.id==='flood'?'Flood impact':c.id==='damage'?'Infrastructure':c.category}</button>)}</div>
  {tileError?<div className="map-offline-note" role="status"><Icon name="info" size={14}/><span>Some tiles are unavailable. Reference imagery is shown.</span><button onClick={()=>setTileRetry(n=>n+1)}>Retry<Icon name="refresh" size={13}/></button></div>:!tileReady&&<div className="map-connection-state" role="status"><Icon name="loader" size={15} className="spin"/>Loading map tiles…</div>}
  <span className="map-demo-tag">DEMO CHANGE OVERLAYS</span>
 </div>;
}
