'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import type { OrganizationRegistration } from '@/lib/types';
import { missionRoute } from '@/lib/presentation';
import { useWorkspace } from './workspace-provider';
import { OrganizationFields } from './organization-fields';
import { SatelliteImage } from './satellite-image';
import { Badge, Button, EmptyState, Icon, Modal, PageHeader } from './ui';

function OnboardingSteps({ step }: { step: number }) { const steps=[{label:'Sign in',href:'/login'},{label:'Organization',href:'/organizations'},{label:'Mission',href:'/missions'},{label:'Dashboard',href:'/'}];return <nav className="onboarding-stepper" aria-label="Workspace setup">{steps.map((s,i)=><Link key={s.href} href={s.href} className={i<step?'complete':i===step?'active':''} aria-current={i===step?'step':undefined}><i>{i<step?<Icon name="check" size={14}/>:i+1}</i><span>{s.label}</span>{i<3&&<Icon name="chevron-right" size={15}/>}</Link>)}</nav>; }
export function OrganizationsPage() {
 const ws=useWorkspace(); const router=useRouter(); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const [creating,setCreating]=useState(false); const [error,setError]=useState('');
 const [draft,setDraft]=useState<OrganizationRegistration>({name:'',typeId:'disaster',location:''});
 const organizations=ws.data.organizations.filter(o=>(filter==='all'||(filter==='mine'?!!o.ownerEmail:!o.ownerEmail))&&`${o.name} ${o.headquarters??''} ${ws.organizationTypes.find(t=>t.id===(o.typeId??o.id))?.name}`.toLowerCase().includes(query.toLowerCase()));
 function create(e:React.FormEvent){e.preventDefault();setError('');try{const org=ws.createOrganization(draft);setCreating(false);ws.notify(`${org.name} is ready. Choose your first mission.`);router.push('/missions');}catch(e){setError(e instanceof Error?e.message:'Unable to create an organization. Please try again.');}}
 return <div><PageHeader eyebrow="WORKSPACE SETUP" title="Choose your organization" description="Open an existing workspace or create one for your team."><Button variant="primary" icon="plus" onClick={()=>{if(!ws.session){router.push('/register');return;}setError('');setDraft({name:'',typeId:ws.organizationType,location:''});setCreating(true);}}>Add organization</Button></PageHeader><OnboardingSteps step={1}/><div className="library-toolbar panel"><div className="input-icon"><Icon name="search"/><input aria-label="Search organizations" placeholder="Search organizations or locations" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Organization filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All available organizations</option><option value="mine">Your organizations</option><option value="demo">Demo organizations</option></select><span>{organizations.length} workspaces</span></div>
 {organizations.length?<div className="organization-grid">{organizations.map(org=><button key={org.id} className={`organization-card panel ${org.id===ws.organizationId?'selected':''}`} onClick={()=>{ws.switchOrganization(org.id);router.push('/missions');}}><div className="organization-card-top"><span className="organization-icon"><Icon name={org.icon} size={25}/></span><Badge tone={org.id===ws.organizationId?'blue':'neutral'}>{org.id===ws.organizationId?'Current workspace':org.ownerEmail?'Your organization':'Demo workspace'}</Badge></div>{org.typeId&&<span className="organization-type-label">{ws.organizationTypes.find(t=>t.id===org.typeId)?.name}</span>}<h2>{org.name}</h2><p>{org.description}</p>{org.headquarters&&<span className="organization-headquarters"><Icon name="pin" size={15}/>{org.headquarters}</span>}<div className="organization-card-bottom"><span>{org.missions.length} mission types</span><span>Open workspace <Icon name="arrow-right" size={16}/></span></div></button>)}</div>:<section className="panel"><EmptyState icon="buildings" title={filter==='mine'?'Create your first organization':'No matching organizations'} description={filter==='mine'?'Give your team its own mission context, saved places, and analysis history.':'Try another name or show all available organizations.'}><Button variant="primary" icon={filter==='mine'?'plus':'refresh'} onClick={()=>{if(filter==='mine')setCreating(true);else{setQuery('');setFilter('all');}}}>{filter==='mine'?'Add organization':'Clear filters'}</Button></EmptyState></section>}
 <div className="organization-note"><Icon name="lock" size={18}/><p>Each organization keeps its own mission, locations, history, reports, and emergency analyses. Registered organizations belong to your local account. Demo workspaces are shared examples in this browser.</p></div>
 {creating&&<Modal title="Add an organization" description="Create a separate workspace under your current local account." onClose={()=>setCreating(false)}><form className="form-stack" onSubmit={create}><OrganizationFields value={draft} onChange={setDraft}/><div className="organization-owner"><Icon name="user" size={17}/><span>Organization owner<strong>{ws.session?.email??'Demo analyst'}</strong></span></div>{error&&<div className="error-banner" role="alert"><Icon name="alert"/><span>{error}</span></div>}<div className="modal-actions"><Button type="button" onClick={()=>setCreating(false)}>Cancel</Button><Button type="submit" variant="primary" icon="plus">Create organization</Button></div></form></Modal>}
 </div>;
}
const descriptions:Record<string,string>={'Flood Analysis':'Map water expansion, review infrastructure exposure, and monitor recovery.','Deforestation Analysis':'Compare canopy coverage and understand where forest landscapes are changing.','Urban Expansion Analysis':'Observe growth in built-up land and surrounding land cover.','Road Development Analysis':'Follow new transport links and linear infrastructure change.','Vegetation Monitoring':'Examine vegetation patterns across multiple observations.'};
export function MissionsPage(){const ws=useWorkspace();const router=useRouter();return <div><PageHeader eyebrow="WORKSPACE SETUP" title="Select your mission" description={`Set the focus for ${ws.organization.name}. Your selection is remembered in this workspace.`}><Link href="/organizations" className="btn btn-secondary"><Icon name="switch" size={16}/>Switch organization</Link></PageHeader><OnboardingSteps step={2}/><div className="mission-selection-layout"><section><span className="eyebrow">AVAILABLE MISSIONS</span><div className="mission-selection-list" role="radiogroup" aria-label="Mission">{ws.missionOptions.map(mission=><button role="radio" aria-checked={ws.mission===mission} className={`panel mission-selection-card ${ws.mission===mission?'selected':''}`} key={mission} onClick={()=>ws.setMission(mission)}><span className="mission-card-icon"><Icon name={missionRoute(mission)==='/emergency'?'shield':ws.organization.icon} size={23}/></span><div><h2>{mission}</h2><p>{descriptions[mission]??`Compare observations, inspect changes, and create a traceable ${mission.toLowerCase()} report.`}</p></div><span className="radio-indicator">{ws.mission===mission&&<span/>}</span></button>)}</div></section><aside className="panel mission-summary"><span className="organization-icon"><Icon name={ws.organization.icon} size={26}/></span><span className="eyebrow">CURRENT ORGANIZATION</span><h2>{ws.organization.name}</h2><p>{ws.organization.headquarters??ws.organization.description}</p><div className="form-stack"><label>Selected mission<input readOnly value={ws.mission}/></label><label>Starting location<select value={ws.location.id} onChange={e=>ws.selectLocation(e.target.value)}>{ws.data.locations.map(l=><option key={l.id} value={l.id}>{l.name}, {l.region}</option>)}</select></label><button type="button" className="mission-summary-image" aria-label={`Explore ${ws.location.name} on the map`} onClick={()=>router.push('/map')}><SatelliteImage src={ws.location.image} alt="Illustrative satellite reference"/><span><Icon name="pin" size={15}/>{ws.location.name}<Icon name="arrow-up-right" size={16}/></span></button><Button variant="primary" icon="arrow-right" onClick={()=>router.push('/')}>Continue to dashboard</Button><Button icon="scan" onClick={()=>router.push(missionRoute(ws.mission))}>Start analysis now</Button></div><div className="mini-disclaimer"><Icon name="info" size={15}/>Demo data / prototype analysis</div></aside></div></div>;}
