'use client';
import { useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Scene, SearchFilters } from '@/lib/types';
import { formatDate } from '@/lib/data-service';
import { categoryMissions, missionRoute } from '@/lib/presentation';
import { Badge, Button, DemoNotice, EmptyState, Icon, Modal, PageHeader, SceneVisual, WorkflowNav } from './ui';
import { useWorkspace } from './workspace-provider';
const initialFilters:SearchFilters={location:'',from:'2025-06-01',to:'2025-06-30',cloud:30,landType:'',source:'',category:''};
const suggestions=['Analyse flood impact','Find deforestation in this region','Show urban expansion near this river','Show new road development','Find infrastructure changes'];
export function SearchPage(){
 const ws=useWorkspace();const router=useRouter();const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('');const [filters,setFilters]=useState<SearchFilters>(initialFilters);const [applied,setApplied]=useState<SearchFilters>(initialFilters);const [results,setResults]=useState<Scene[]>(ws.data.scenes);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [sort,setSort]=useState('relevance');const [view,setView]=useState('grid');const [limit,setLimit]=useState(6);const [filterOpen,setFilterOpen]=useState(true);const [preview,setPreview]=useState<Scene|null>(null);const requestId=useRef(0);
 const sorted=useMemo(()=>[...results].sort((a,b)=>sort==='date'?b.date.localeCompare(a.date):sort==='cloud'?a.cloud-b.cloud:b.relevance-a.relevance),[results,sort]);const dirty=JSON.stringify(applied)!==JSON.stringify(filters);
 async function runSearch(value=query,selectedFilters=filters){const token=++requestId.current;setLoading(true);setError('');setLimit(6);try{const response=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:value,filters:selectedFilters})});const result=await response.json();if(!response.ok)throw new Error(result.error);if(token!==requestId.current)return;setResults(result.scenes);setSubmitted(value);setApplied({...selectedFilters});}catch(e){if(token===requestId.current)setError(e instanceof Error?e.message:'Unable to retrieve scenes. Please try again.');}finally{if(token===requestId.current)setLoading(false);}}
 function updateFilter<K extends keyof SearchFilters>(key:K,value:SearchFilters[K]){setFilters(previous=>({...previous,[key]:value}));}
 function prepare(scene:Scene,compare=false){ws.selectScene(scene.id);const mission=categoryMissions[scene.category]??ws.mission;ws.setMission(mission);router.push(`${compare?'/temporal':missionRoute(mission)}?scene=${scene.id}`);}
 function mapScene(scene:Scene){ws.selectScene(scene.id);router.push('/map?tab=imagery');}
 function reset(){setFilters(initialFilters);setQuery('');runSearch('',initialFilters);}
 const previewLocation=preview?ws.data.locations.find(l=>l.id===preview.locationId):null;
 return <div><PageHeader eyebrow="SATELLITE DISCOVERY" title="Semantic search" description="Describe what you’re looking for, then refine your imagery by location and date."><Badge tone="blue"><Icon name="sparkles" size={15}/>Natural-language discovery</Badge></PageHeader><WorkflowNav current="search"/>
 <section className="search-hero panel"><form onSubmit={e=>{e.preventDefault();runSearch();}}><Icon name="search" size={23}/><input aria-label="Natural-language satellite search" placeholder="What would you like to observe?" value={query} maxLength={500} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" className="icon-button" onClick={()=>setQuery('')} aria-label="Clear search query"><Icon name="x" size={18}/></button>}<Button variant="primary" icon="search" type="submit" loading={loading}>Find imagery</Button></form><div className="search-suggestions"><span>Try a search</span>{suggestions.map(s=><button key={s} onClick={()=>{setQuery(s);runSearch(s);}}>{s}<Icon name="arrow-up-right" size={13}/></button>)}</div></section>
 <DemoNotice/><div className={`search-layout ${!filterOpen?'filters-hidden':''}`}><aside className="panel search-filters" id="search-filters"><div className="panel-heading"><h2><Icon name="sliders" size={18}/>Filters</h2><button className="text-button" onClick={reset}>Reset all</button></div><form className="form-stack" onSubmit={e=>{e.preventDefault();runSearch();}}><label>Location<select aria-label="Location filter" value={filters.location} onChange={e=>updateFilter('location',e.target.value)}><option value="">All locations</option>{ws.data.locations.map(l=><option key={l.id} value={l.id}>{l.name}, {l.region}</option>)}</select></label><label>Observation period<div className="date-input-stack"><input aria-label="Search start date" type="date" value={filters.from} onChange={e=>updateFilter('from',e.target.value)}/><input aria-label="Search end date" type="date" value={filters.to} min={filters.from} onChange={e=>updateFilter('to',e.target.value)}/></div></label><label>Cloud coverage<span className="range-value">Up to {filters.cloud}%</span><input aria-label="Maximum cloud coverage" className="range-input" type="range" min="0" max="100" value={filters.cloud} onChange={e=>updateFilter('cloud',Number(e.target.value))}/><span className="range-endpoints"><span>Clear</span><span>Cloudy</span></span></label><label>Land type<select aria-label="Land type" value={filters.landType} onChange={e=>updateFilter('landType',e.target.value)}><option value="">All land types</option>{Array.from(new Set(ws.data.locations.map(l=>l.landType))).map(l=><option key={l}>{l}</option>)}</select></label><label>Satellite source<select aria-label="Satellite source" value={filters.source} onChange={e=>updateFilter('source',e.target.value)}><option value="">All satellite sources</option>{Array.from(new Set(ws.data.scenes.map(s=>s.source))).map(s=><option key={s}>{s}</option>)}</select></label><label>Change category<select aria-label="Change category" value={filters.category} onChange={e=>updateFilter('category',e.target.value)}><option value="">All categories</option>{ws.data.changes.map(c=><option key={c.id}>{c.category}</option>)}</select></label><Button variant="primary" icon="filter" loading={loading} type="submit">Apply filters{dirty&&<span className="pending-filter-dot"/>}</Button>{dirty&&<p className="filter-pending" role="status">Filters changed. Apply to update results.</p>}</form><div className="filter-method-note"><Icon name="info" size={17}/><p>Prototype relevance uses keyword and tag matching over the demo catalog, not a trained semantic model.</p></div></aside>
 <section className="search-results" aria-busy={loading}><div className="results-toolbar"><div><button className={`icon-button ${filterOpen?'active':''}`} aria-label="Toggle filters" aria-expanded={filterOpen} aria-controls="search-filters" onClick={()=>setFilterOpen(!filterOpen)}><Icon name="sliders" size={19}/></button><h2 aria-live="polite">{loading?'Finding imagery…':`${results.length} satellite scenes`}</h2></div><div><select aria-label="Sort satellite scenes" value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Most relevant</option><option value="date">Newest first</option><option value="cloud">Lowest cloud cover</option></select><div className="view-toggle"><button className={view==='grid'?'selected':''} aria-label="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><Icon name="grid" size={18}/></button><button className={view==='list'?'selected':''} aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><Icon name="menu" size={18}/></button></div></div></div>{submitted&&<p className="search-query-summary">Results for <strong>“{submitted}”</strong></p>}
 {error?<div className="panel"><EmptyState title="We couldn’t retrieve imagery" description={error} icon="alert"><Button icon="refresh" onClick={()=>runSearch()}>Try again</Button></EmptyState></div>:loading?<div className="scene-results-grid" role="status" aria-label="Loading satellite scenes">{[1,2,3,4].map(n=><div className="scene-skeleton panel" key={n}><div/><span/><span/></div>)}</div>:!results.length?<div className="panel"><EmptyState title="No scenes match this search" description="Try a broader description, increase cloud coverage, or reset the location and date filters."><Button icon="refresh" onClick={reset}>Reset search</Button></EmptyState></div>:<div className={`scene-results-grid ${view==='list'?'scene-results-list':''}`}>{sorted.slice(0,limit).map(scene=>{const location=ws.data.locations.find(l=>l.id===scene.locationId)!;return <article key={scene.id} className="scene-card panel"><div className="scene-card-image"><button className="scene-preview-trigger" aria-label={`Preview ${scene.title}`} onClick={()=>setPreview(scene)}><SceneVisual image={scene.image} stage={scene.stage} category={scene.category} label={`${location.name}, ${location.region}`}/><span className="scene-preview-affordance"><Icon name="expand" size={17}/>Preview scene</span></button><Badge tone="blue">{scene.relevance}% relevance</Badge><button className={`scene-save ${ws.savedScenes.includes(scene.id)?'saved':''}`} onClick={()=>ws.toggleScene(scene.id)} aria-pressed={ws.savedScenes.includes(scene.id)} aria-label={`${ws.savedScenes.includes(scene.id)?'Unsave':'Save'} ${scene.title}`} title={ws.savedScenes.includes(scene.id)?'Remove saved scene':'Save this scene'}><Icon name={ws.savedScenes.includes(scene.id)?'check':'bookmark'} size={18}/></button><span className="scene-demo">DEMO SCENE</span></div><div className="scene-card-body"><div className="scene-category">{scene.category}</div><h3><button onClick={()=>setPreview(scene)}>{scene.title}</button></h3><div className="scene-meta"><span><Icon name="calendar" size={14}/>{formatDate(scene.date)}</span><span><Icon name="satellite" size={14}/>{scene.source}</span><span><Icon name="cloud" size={14}/>{scene.cloud}%</span></div><p>{scene.description}</p><div className="scene-actions"><Button icon="map" onClick={()=>mapScene(scene)}>View map</Button><Button icon="layers" onClick={()=>prepare(scene,true)}>Compare</Button><Button variant="primary" icon="scan" onClick={()=>prepare(scene)}>Analyze</Button></div></div></article>;})}</div>}
 {limit<sorted.length&&!loading&&<div className="load-more"><Button icon="plus" onClick={()=>setLimit(previous=>previous+6)}>Load more scenes <span>({sorted.length-limit} remaining)</span></Button></div>}</section></div>
 {preview&&previewLocation&&<Modal wide title={preview.title} description={`${previewLocation.name}, ${previewLocation.region} · ${preview.id}`} onClose={()=>setPreview(null)}><div className="scene-preview-large"><SceneVisual image={preview.image} stage={preview.stage} category={preview.category} label={previewLocation.name}/></div><div className="scene-preview-metadata"><span><Icon name="calendar" size={16}/>{formatDate(preview.date)}</span><span><Icon name="satellite" size={16}/>{preview.source}</span><span><Icon name="cloud" size={16}/>{preview.cloud}% cloud</span><Badge tone="blue">{preview.relevance}% relevance</Badge></div><p className="scene-preview-description">{preview.description}</p><DemoNotice/><div className="modal-actions"><Button icon={ws.savedScenes.includes(preview.id)?'check':'bookmark'} onClick={()=>ws.toggleScene(preview.id)}>{ws.savedScenes.includes(preview.id)?'Saved':'Save scene'}</Button><Button icon="map" onClick={()=>mapScene(preview)}>View map</Button><Button icon="layers" onClick={()=>prepare(preview,true)}>Compare</Button><Button variant="primary" icon="scan" onClick={()=>prepare(preview)}>Analyze</Button></div></Modal>}
 </div>;
}
