'use client';
import Link from 'next/link';
import { useEffect, useId, useRef, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { Activity, ArrowDown, ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpRight, Bell, BookOpen, Bookmark, Building2, CalendarDays, Check, CheckCheck, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, CircleHelp, CircleUserRound, Clock3, Cloud, CloudLightning, Compass, Copy, Crosshair, Download, Expand, ExternalLink, Eye, EyeOff, FileText, Filter, Flame, FolderOpen, Globe2, Grid2X2, History, Info, Layers3, LayoutDashboard, Leaf, Loader2, LocateFixed, LockKeyhole, LogOut, Mail, Map, MapPin, Maximize2, Menu, Minus, Monitor, MoreHorizontal, Mountain, Orbit, PanelLeftClose, Play, Plus, Radio, Radar, RefreshCw, Route, Satellite, Save, ScanLine, Search, Settings2, Shield, ShieldCheck, SlidersHorizontal, Sparkles, Sprout, SquareDashedMousePointer, Target, Trash2, Trees, TriangleAlert, Waves, Wind, X, Zap } from 'lucide-react';
import { interpretationNotice } from '@/lib/data-service';
import { SatelliteImage } from './satellite-image';
const icons = { activity:Activity, arrowDown:ArrowDown, download:Download, 'arrow-left':ArrowLeft, 'arrow-right':ArrowRight, 'arrow-up-right':ArrowUpRight, bell:Bell, book:BookOpen, bookmark:Bookmark, buildings:Building2, calendar:CalendarDays, check:Check, checks:CheckCheck, 'check-circle':CheckCircle2, chevron:ChevronDown, 'chevron-right':ChevronRight, 'chevron-left':ChevronLeft, switch:ChevronsUpDown, help:CircleHelp, user:CircleUserRound, clock:Clock3, cloud:Cloud, 'cloud-lightning':CloudLightning, compass:Compass, copy:Copy, crosshair:Crosshair, expand:Expand, external:ExternalLink, eye:Eye, 'eye-off':EyeOff, file:FileText, filter:Filter, flame:Flame, folder:FolderOpen, globe:Globe2, grid:Grid2X2, history:History, info:Info, layers:Layers3, dashboard:LayoutDashboard, leaf:Leaf, loader:Loader2, locate:LocateFixed, lock:LockKeyhole, logout:LogOut, mail:Mail, map:Map, pin:MapPin, maximize:Maximize2, menu:Menu, minus:Minus, monitor:Monitor, more:MoreHorizontal, mountain:Mountain, orbit:Orbit, collapse:PanelLeftClose, play:Play, plus:Plus, radio:Radio, radar:Radar, refresh:RefreshCw, route:Route, satellite:Satellite, save:Save, scan:ScanLine, search:Search, settings:Settings2, shield:Shield, 'shield-check':ShieldCheck, sliders:SlidersHorizontal, sparkles:Sparkles, sprout:Sprout, aoi:SquareDashedMousePointer, target:Target, trash:Trash2, trees:Trees, alert:TriangleAlert, waves:Waves, wind:Wind, x:X, zap:Zap, export:ArrowDownToLine };
export function Icon({ name, size = 18, className = '', strokeWidth = 1.8 }: { name: string; size?: number; className?: string; strokeWidth?: number }) { const Component=icons[name as keyof typeof icons]??Globe2;return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true"/>; }
export function Button({children,variant='secondary',icon,className='',loading,type='button',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger';icon?:string;loading?:boolean}){return <button {...props} type={type} aria-busy={loading||undefined} disabled={props.disabled||loading} className={`btn btn-${variant} ${className}`}>{loading?<Icon name="loader" className="spin" size={17}/>:icon?<Icon name={icon} size={17}/>:null}{children}</button>;}
export function Badge({children,tone='neutral',dot=false}:{children:ReactNode;tone?:string;dot?:boolean}){return <span className={`badge badge-${tone}`}>{dot&&<span className="status-dot"/>}{children}</span>;}
export function PageHeader({eyebrow,title,description,children}:{eyebrow?:string;title:string;description:string;children?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div>{children&&<div className="heading-actions">{children}</div>}</div>;}
export function DemoNotice({compact=false}:{compact?:boolean}){return <div className={`demo-notice ${compact?'compact':''}`}><Icon name="info" size={17}/><span><strong>DEMO DATA / PROTOTYPE ANALYSIS</strong>{!compact&&' — Illustrative imagery and simulated results. Not for operational use.'}</span></div>;}
export function EmptyState({title,description,icon='search',children}:{title:string;description:string;icon?:string;children?:ReactNode}){return <div className="empty-state"><span className="empty-icon"><Icon name={icon} size={28}/></span><h3>{title}</h3><p>{description}</p>{children}</div>;}
export function Modal({title,description,children,onClose,wide=false}:{title:string;description?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const dialog=useRef<HTMLDivElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;const titleId=useId();const descriptionId=useId();
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow='hidden';const initial=dialog.current?.querySelector<HTMLElement>('.modal-content input:not([type=checkbox]):not(:disabled), .modal-content select:not(:disabled), .modal-content button:not(:disabled)');(initial??dialog.current)?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();closeRef.current();}if(e.key==='Tab'&&dialog.current){const targets=Array.from(dialog.current.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex="0"]')).filter(el=>el.offsetParent!==null);const first=targets[0],last=targets[targets.length-1];if(!targets.length){e.preventDefault();dialog.current.focus();}else if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',handle);if(previous?.isConnected)previous.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className={`modal ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={description?descriptionId:undefined} ref={dialog} tabIndex={-1}><div className="modal-heading"><div><h2 id={titleId}>{title}</h2>{description&&<p id={descriptionId}>{description}</p>}</div><button type="button" className="icon-button" aria-label="Close dialog" onClick={onClose}><Icon name="x" size={21}/></button></div><div className="modal-content">{children}</div></div></div>;
}
export function SceneVisual({image,stage='before',category='Flooding',mask=true,className='',label}:{image:string;stage?:string;category?:string;mask?:boolean;className?:string;label?:string}){
 const forest=/forest|Vegetation|Agricultural/.test(category);const recovery=stage==='after'||stage==='recovery';
 return <div className={`scene-visual scene-${stage} ${className}`} data-observation={stage}><SatelliteImage src={image} alt={`Illustrative satellite basemap${label?` of ${label}`:''}; simulated ${stage} scene`}/><div className="scene-vignette"/>{mask&&stage!=='before'&&<svg className={`scene-mask ${recovery?'mask-recovery':''}`} viewBox="0 0 600 400" preserveAspectRatio="none" aria-label="Simulated change mask"><g fill={recovery?'#37a886':'#4b9cfa'} fillOpacity=".33" stroke={recovery?'#7ee1b4':'#96caff'} strokeWidth="1.8" strokeDasharray="5 3"><path d={forest?'M320 54 L382 72 L374 143 L326 158 L295 103 Z M189 245 L268 211 L295 284 L247 332 L179 305 Z':'M215 4 L249 25 L231 89 L282 113 L258 155 L301 211 L285 268 L349 336 L339 402 L292 395 L275 321 L241 284 L250 231 L211 180 L228 125 L192 83 Z'}/><path d="M388 169 L441 150 L475 187 L448 232 L397 220 L376 199 Z"/></g></svg>}{label&&<span className="scene-location-label"><Icon name="pin" size={14}/>{label}</span>}</div>;
}
export function InsightPanel({insight}:{insight:string}){return <section className="insight-panel"><div className="insight-title"><span className="insight-icon"><Icon name="sparkles" size={21}/></span><h3>AI-Assisted Insight</h3><Badge tone="blue">Prototype interpretation</Badge></div><p>{insight}</p><div className="insight-disclaimer"><Icon name="shield-check" size={17}/><span>{interpretationNotice}</span></div></section>;}
export function Brand({dark=false}:{dark?:boolean}){return <div className={`brand ${dark?'brand-dark':''}`}><span className="brand-symbol"><Icon name="orbit" size={33} strokeWidth={1.7}/><span/></span><div><span className="brand-name">orbital<span className="brand-period">.</span></span><span className="brand-tagline">GEOSPATIAL INTELLIGENCE</span></div></div>;}
export function WorkspaceLoading(){return <div className="workspace-loading" role="status" aria-busy="true"><span className="sr-only">Restoring your workspace…</span><div className="loading-heading"/><div className="loading-subheading"/><div className="loading-stats">{[1,2,3,4].map(i=><div key={i}/>)}</div><div className="loading-map"><Icon name="satellite" size={30}/><span>Preparing your workspace…</span></div></div>;}
export function WorkflowNav({current,emergency=false}:{current:string;emergency?:boolean}){const steps=emergency?[{id:'emergency',label:'Event & impact',href:'/emergency',icon:'shield'},{id:'map',label:'Explore map',href:'/map',icon:'map'},{id:'reports',label:'Reports',href:'/reports',icon:'file'}]:[{id:'search',label:'Find imagery',href:'/search',icon:'search'},{id:'map',label:'Explore map',href:'/map',icon:'map'},{id:'temporal',label:'Compare dates',href:'/temporal',icon:'layers'},{id:'changes',label:'Detect changes',href:'/changes',icon:'scan'},{id:'reports',label:'Reports',href:'/reports',icon:'file'}];return <nav className="workflow-nav" aria-label={emergency?'Emergency workflow':'Analysis workflow'}>{steps.map((s,i)=><Link key={s.id} href={s.href} className={current===s.id?'active':''} aria-current={current===s.id?'step':undefined}><span className="workflow-number">{i+1}</span><Icon name={s.icon} size={16}/><span>{s.label}</span>{i<steps.length-1&&<Icon name="chevron-right" size={14}/>}</Link>)}</nav>;}
