'use client';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import { missionRoute } from '@/lib/presentation';
import { Badge, Brand, Button, EmptyState, Icon, Modal, WorkspaceLoading } from './ui';
import { useWorkspace } from './workspace-provider';

export const navigation = [
 { href: '/', label: 'Dashboard', icon: 'dashboard', group: 'WORKSPACE' },
 { href: '/search', label: 'Semantic search', icon: 'search', group: 'WORKSPACE' },
 { href: '/map', label: 'Map explorer', icon: 'map', group: 'WORKSPACE' },
 { href: '/temporal', label: 'Temporal analysis', icon: 'layers', group: 'WORKSPACE' },
 { href: '/emergency', label: 'Emergency analysis', icon: 'shield', group: 'WORKSPACE' },
 { href: '/changes', label: 'Change detection', icon: 'scan', group: 'WORKSPACE' },
 { href: '/reports', label: 'Reports', icon: 'file', group: 'LIBRARY' },
 { href: '/history', label: 'Analysis history', icon: 'history', group: 'LIBRARY' },
 { href: '/saved', label: 'Saved locations', icon: 'bookmark', group: 'LIBRARY' },
];
const backLinks: Record<string, { href: string; label: string }> = { '/organizations': { href: '/', label: 'Back to dashboard' }, '/missions': { href: '/organizations', label: 'Back to organizations' }, '/map': { href: '/search', label: 'Back to search' }, '/temporal': { href: '/map', label: 'Back to map' }, '/changes': { href: '/temporal', label: 'Back to comparison' } };

function BackNavigation(){
 const path=usePathname();const params=useSearchParams();const router=useRouter();const ws=useWorkspace();
 if(path==='/'||path==='/dashboard')return null;
 const reportPreview=path==='/reports'&&!!ws.activeReportId;
 const back=params.has('analysis')?{href:'/history',label:'Back to analysis history'}:backLinks[path]??{href:'/',label:'Back to dashboard'};
 const label=reportPreview?'Back to reports':back.label;
 return <button className="icon-button back-button" aria-label={label} title={label} onClick={()=>{if(reportPreview)ws.setActiveReportId(null);else router.push(back.href);}}><Icon name="arrow-left" size={18}/></button>;
}

function NewAnalysisDialog() {
 const ws=useWorkspace(); const router=useRouter();
 const [orgId,setOrgId]=useState(ws.organizationId);const [mission,setMission]=useState(ws.mission);const [locationId,setLocationId]=useState(ws.location.id);
 const org=ws.data.organizations.find(o=>o.id===orgId)!;
 const missions=Array.from(new Set([...org.missions,...(orgId===ws.organizationId?[ws.mission]:[])]));
 return <Modal title="Start a new analysis" description="Choose the organization, mission, and area you want to observe." onClose={()=>ws.setNewAnalysisOpen(false)}><form className="form-stack" onSubmit={e=>{e.preventDefault();ws.configureWorkspace(orgId,mission,locationId);ws.setNewAnalysisOpen(false);router.push(missionRoute(mission));}}><label>Organization<select aria-label="Organization" value={orgId} onChange={e=>{const next=ws.data.organizations.find(o=>o.id===e.target.value)!;setOrgId(next.id);setMission(next.missions[0]);if(next.homeLocationId)setLocationId(next.homeLocationId);}}>{ws.data.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Mission<select aria-label="Mission" value={mission} onChange={e=>setMission(e.target.value)}>{missions.map(m=><option key={m}>{m}</option>)}</select></label><label>Area of interest<select aria-label="Area of interest" value={locationId} onChange={e=>setLocationId(e.target.value)}>{ws.data.locations.map(l=><option key={l.id} value={l.id}>{l.name}, {l.region} · {l.country}</option>)}</select></label><div className="inline-note"><Icon name="info" size={18}/><p>You’ll select observation dates next. All analysis findings use clearly labeled demo data.</p></div><div className="modal-actions"><Button onClick={()=>ws.setNewAnalysisOpen(false)}>Cancel</Button><Button variant="primary" icon="arrow-right" type="submit">Configure analysis</Button></div></form></Modal>;
}
export function WorkspaceShell({children}:{children:ReactNode}) {
 const path=usePathname();const router=useRouter();const ws=useWorkspace();
 const [mobile,setMobile]=useState(false);const [orgMenu,setOrgMenu]=useState(false);const [notifications,setNotifications]=useState(false);const [read,setRead]=useState(false);const [guide,setGuide]=useState(false);const [command,setCommand]=useState(false);const [query,setQuery]=useState('');
 const orgRef=useRef<HTMLDivElement>(null);const notificationRef=useRef<HTMLDivElement>(null);const sidebarRef=useRef<HTMLElement>(null);
 const current=navigation.find(n=>n.href===path)?.label??(path==='/settings'?'Settings':path==='/organizations'?'Organizations':path==='/missions'?'Mission selection':'Dashboard');
 const initials=(ws.session?.name??'Demo Analyst').split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase();
 const matchingPages=navigation.filter(n=>n.label.toLowerCase().includes(query.toLowerCase()));
 const matchingLocations=ws.data.locations.filter(l=>`${l.name} ${l.region}`.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{setMobile(false);setOrgMenu(false);setNotifications(false);},[path]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!orgRef.current?.contains(e.target as Node))setOrgMenu(false);if(!notificationRef.current?.contains(e.target as Node))setNotifications(false);};const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommand(previous=>!previous);}if(e.key==='Escape'){setOrgMenu(false);setNotifications(false);setMobile(false);}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',keys);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',keys);};},[]);
 useEffect(()=>{if(!mobile)return;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';sidebarRef.current?.querySelector<HTMLElement>('a')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const elements=Array.from(sidebarRef.current?.querySelectorAll<HTMLElement>('a[href], button:not(:disabled)')??[]).filter(el=>el.offsetParent!==null);const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',trap);previous?.focus();};},[mobile]);
 function selectOrg(id:string){const org=ws.data.organizations.find(o=>o.id===id)!;ws.switchOrganization(id);setOrgMenu(false);setMobile(false);ws.notify(`Switched to ${org.name}. Your mission context is restored.`);router.push('/');}
 return <div className={`app-shell ${ws.preferences.compact?'density-compact':''}`}><a className="skip-link" href="#workspace-content">Skip to workspace content</a>
  {mobile&&<div className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}
  <aside ref={sidebarRef} className={`sidebar ${mobile?'sidebar-open':''}`} aria-label="Workspace navigation"><div className="sidebar-brand-row"><Link href="/" className="brand-link" aria-label="Orbital dashboard"><Brand/></Link><button className="mobile-sidebar-close icon-button" onClick={()=>setMobile(false)} aria-label="Close navigation"><Icon name="x"/></button></div>
   <div className="workspace-picker-wrap" ref={orgRef}><button className="workspace-picker" onClick={()=>setOrgMenu(!orgMenu)} aria-expanded={orgMenu} aria-controls="organization-menu" title="Switch organization"><span className="workspace-icon"><Icon name={ws.organization.icon} size={20}/></span><span><small>Organization</small><strong>{ws.organization.shortName}</strong></span><Icon name="switch" size={15}/></button>
    {orgMenu&&<div className="org-popover" id="organization-menu" aria-label="Available organizations"><div className="popover-label">SWITCH ORGANIZATION</div><div className="org-popover-list">{ws.data.organizations.map(o=><button key={o.id} className={o.id===ws.organizationId?'selected':''} onClick={()=>selectOrg(o.id)} aria-pressed={o.id===ws.organizationId}><Icon name={o.icon} size={18}/><span>{o.shortName}{o.ownerEmail&&<small>Your organization</small>}</span>{o.id===ws.organizationId&&<Icon name="check" size={16}/>}</button>)}</div><Link href="/organizations" onClick={()=>{setOrgMenu(false);setMobile(false);}}><Icon name="buildings" size={16}/>Manage organizations<Icon name="arrow-up-right" size={15}/></Link></div>}
   </div>
   <Link className="sidebar-mission" href="/missions" onClick={()=>setMobile(false)}><Icon name="target" size={17}/><span><small>Current mission</small><strong>{ws.mission}</strong></span><Icon name="chevron-right" size={14}/></Link>
   <nav className="main-nav" aria-label="Main navigation">{['WORKSPACE','LIBRARY'].map(group=><div className="nav-group" key={group}><p className="nav-group-label">{group}</p>{navigation.filter(n=>n.group===group).map(item=>{const active=path===item.href||(path==='/dashboard'&&item.href==='/');return <Link key={item.href} href={item.href} aria-current={active?'page':undefined} onClick={()=>setMobile(false)} className={`nav-item ${active?'active':''}`}><Icon name={item.icon} size={19}/><span>{item.label}</span>{item.href==='/reports'&&<span className="nav-count">{ws.reports.length}</span>}</Link>;})}</div>)}</nav>
   <div className="sidebar-bottom"><button className="nav-item sidebar-help" onClick={()=>{setGuide(true);setMobile(false);}}><Icon name="help" size={18}/><span>Platform guide</span><Icon name="arrow-up-right" size={14}/></button><Link href="/settings" className={`nav-item ${path==='/settings'?'active':''}`} aria-current={path==='/settings'?'page':undefined} onClick={()=>setMobile(false)}><Icon name="settings" size={18}/><span>Settings & preferences</span></Link><div className="sidebar-profile"><span className="avatar">{initials}</span><Link href="/settings"><strong>{ws.session?.name??'Demo analyst'}</strong><small>{ws.session?.role??'Preview workspace'}</small></Link><button onClick={()=>{ws.setSession(null);router.push('/login');}} aria-label="Sign out" title="Sign out"><Icon name="logout" size={18}/></button></div></div>
  </aside>
  <div className="workspace-main"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation" aria-expanded={mobile}><Icon name="menu" size={21}/></button><Suspense fallback={null}><BackNavigation/></Suspense><Link href="/" className="breadcrumb-home"><Icon name="grid" size={16}/><span>Workspace</span></Link><Icon name="chevron-right" size={13}/><strong aria-current="page">{current}</strong>{path==='/reports'&&ws.activeReportId&&<><Icon name="chevron-right" size={13}/><span>Preview</span></>}</div><div className="topbar-actions"><span className="demo-workspace"><Icon name="info" size={14}/>Demo workspace</span><button className="workspace-command" aria-label="Search workspace" onClick={()=>{setQuery('');setCommand(true);}}><Icon name="search" size={17}/><span>Search</span><kbd>⌘ K</kbd></button><div className="notification-wrap" ref={notificationRef}><button className="icon-button notification-button" aria-label="Notifications" aria-expanded={notifications} onClick={()=>setNotifications(!notifications)}><Icon name="bell" size={20}/>{!read&&ws.preferences.notifications&&<span/>}</button>{notifications&&<div className="notification-popover"><div className="popover-heading"><strong>Workspace updates</strong><button onClick={()=>{setRead(true);ws.notify('All notifications marked as read.');}} aria-label="Mark all notifications as read" title="Mark all as read"><Icon name="checks" size={19}/></button></div>{read?<div className="notification-empty"><Icon name="check-circle" size={27}/><h3>You’re all caught up.</h3><p>New workspace updates will appear here.</p></div>:<><Link href="/emergency" onClick={()=>setNotifications(false)}><span className="notice-icon blue"><Icon name="shield"/></span><div><strong>Emergency analysis is ready</strong><p>Review event impact in your current organization.</p><small>Prototype workflow</small></div></Link><Link href="/reports" onClick={()=>setNotifications(false)}><span className="notice-icon blue"><Icon name="file"/></span><div><strong>Your evidence, in one place</strong><p>View and download your workspace reports.</p><small>{ws.organization.name}</small></div></Link></>}</div>}</div><span className="header-divider"/><Link href="/settings" className="avatar header-avatar" aria-label="Profile settings">{initials}</Link></div></header>
   <div className="mobile-workspace-context"><Link href="/organizations"><Icon name={ws.organization.icon} size={15}/>{ws.organization.name}</Link><Icon name="chevron-right" size={12}/><Link href="/missions">{ws.mission}<Icon name="chevron" size={13}/></Link></div>
   <main id="workspace-content" className="page-content" tabIndex={-1}>{ws.ready?<div key={path} className="page-transition">{children}</div>:<WorkspaceLoading/>}</main>
   <footer className="workspace-footer"><div><Icon name="shield-check" size={15}/><span>DEMO DATA / PROTOTYPE ANALYSIS</span><i/>Not for operational decisions.</div><span>Orbital <span className="version">v1.0</span></span></footer>
  </div>
  {ws.toast&&<div role={ws.toast.type==='error'?'alert':'status'} className={`toast toast-${ws.toast.type}`}><Icon name={ws.toast.type==='error'?'alert':ws.toast.type==='success'?'check-circle':'info'} size={20}/><span>{ws.toast.message}</span><button onClick={()=>ws.setToast(null)} aria-label="Dismiss notification"><Icon name="x" size={17}/></button></div>}
  {ws.newAnalysisOpen&&<NewAnalysisDialog/>}
  {guide&&<Modal title="Your mission, from imagery to insight" description="A quick guide to the existing Orbital workflows." onClose={()=>setGuide(false)}><div className="guide-steps">{[{n:'01',title:'Choose an organization and mission',text:'Create a local organization or explore a demo workspace. Your mission and saved work are remembered separately.'},{n:'02',title:'Search and select your imagery',text:'Search in plain language, open a location on the map, and select a scene from its imagery list.'},{n:'03',title:'Compare and understand the change',text:'Choose dates, inspect the timeline, run a prototype analysis, and review mapped evidence and interpretation.'},{n:'04',title:'Generate a shareable report',text:'Open the report preview and download a PDF. Reopen completed work from Analysis history.'}].map(s=><div key={s.n}><span>{s.n}</span><section><h3>{s.title}</h3><p>{s.text}</p></section></div>)}</div><div className="inline-note"><Icon name="info"/><p>All results are simulated. Work is stored in this browser, and sign-in is for demonstration only.</p></div><div className="modal-actions"><Link href="/welcome" className="btn btn-secondary" onClick={()=>setGuide(false)}>About the platform</Link><Button variant="primary" icon="play" onClick={()=>{setGuide(false);ws.configureWorkspace('disaster','Flood Analysis','kochi');router.push('/emergency');}}>Try the flood demo</Button></div></Modal>}
  {command&&<Modal title="Search your workspace" description="Find a page or jump to a catalog location. Shortcut: Ctrl / ⌘ K." onClose={()=>setCommand(false)}><div className="input-icon"><Icon name="search"/><input autoFocus aria-label="Search pages and locations" placeholder="Search pages, locations…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="command-results">{matchingPages.map(n=><Link key={n.href} href={n.href} onClick={()=>setCommand(false)}><Icon name={n.icon}/><span>{n.label}</span><Icon name="arrow-up-right" size={16}/></Link>)}{matchingLocations.map(l=><button key={l.id} onClick={()=>{ws.selectLocation(l);setCommand(false);router.push('/map');}}><Icon name="pin"/><span>{l.name}, {l.region}</span><Badge>Location</Badge></button>)}{!matchingPages.length&&!matchingLocations.length&&<EmptyState title="No matches yet" description="Try a page name, city, or region."/>}</div></Modal>}
 </div>;
}
