import { chromium, expect } from '@playwright/test';
import { mkdir, readFile } from 'node:fs/promises';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3000';
await mkdir('artifacts/ux',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async route=>{await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.waitForTimeout(350);};
const shot=async(name,fullPage=false)=>page.screenshot({path:`artifacts/ux/${name}.png`,fullPage});
const orgMenu=()=>page.locator('.workspace-picker');
async function chooseOrg(name){await orgMenu().click();await page.locator('.org-popover-list>button').filter({hasText:name}).click();await page.waitForURL(base+'/');await expect(orgMenu()).toContainText(name);}
async function runAnalysis(emergency=true){await page.getByRole('button',{name:'WHAT CHANGED HERE?',exact:true}).click();await expect(page.locator('.analysis-results')).toBeVisible({timeout:15000});await expect(page.getByRole('heading',{name:'AI-Assisted Insight',exact:true})).toBeVisible();if(emergency)await expect(page.getByRole('heading',{name:'Impact assessment',exact:true})).toBeVisible();}
async function pdfDownload(name){const promise=page.waitForEvent('download');await page.getByRole('button',{name:'Download PDF',exact:true}).click();const download=await promise;await download.saveAs(`artifacts/ux/${name}.pdf`);const bytes=await readFile(`artifacts/ux/${name}.pdf`);if(bytes.toString('ascii',0,4)!=='%PDF'||bytes.length<50000)throw new Error('Invalid PDF export');return bytes;}
try{
 await go('/');await expect(page.getByRole('heading',{name:'Workspace overview',exact:true})).toBeVisible();await page.waitForTimeout(1200);await shot('dashboard-desktop');console.log('PASS: refreshed desktop dashboard');
 const navFont=await page.locator('.nav-item').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize));if(navFont<12)throw new Error(`Navigation font too small: ${navFont}`);
 await page.getByRole('button',{name:'New analysis',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Organization',{exact:true}).selectOption('environment');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(orgMenu()).toContainText('Disaster Management');console.log('PASS: cancelled configuration preserves organization');
 await page.keyboard.press('Control+k');await expect(page.getByRole('dialog',{name:'Search your workspace'})).toBeVisible();await page.getByRole('textbox',{name:'Search pages and locations'}).fill('no-such-place');await expect(page.getByRole('heading',{name:'No matches yet'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.locator('.stat-card').first().click();await page.waitForURL('**/search');await page.getByRole('button',{name:'Analyse flood impact',exact:true}).click();await expect(page.locator('.scene-card')).toHaveCount(4);await page.locator('.scene-preview-trigger').first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Save scene',exact:true}).click();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByLabel('Satellite source',{exact:true}).selectOption('Landsat-9');await expect(page.getByText('Filters changed. Apply to update results.')).toBeVisible();await page.getByRole('button',{name:'Apply filters',exact:false}).click();await expect(page.locator('.scene-card')).toHaveCount(1);await page.getByRole('button',{name:'View map',exact:true}).click();await page.waitForURL('**/map?tab=imagery');await expect(orgMenu()).toContainText('Disaster Management');await expect(page.getByRole('tab',{name:/Imagery/})).toHaveAttribute('aria-selected','true');await expect(page.locator('.map-scene-item')).toHaveCount(3);await page.locator('.map-scene-item').first().click();await expect(page.locator('.map-reference-label')).toHaveText('Before');await page.locator('.map-scene-item').nth(1).click();await expect(page.locator('.map-reference-label')).toHaveText('Observation');await shot('map-desktop');console.log('PASS: search filtering, scene previews, saving, map imagery selection');
 await page.getByRole('button',{name:'Map layers',exact:true}).click();await expect(page.locator('.map-layers-panel')).toBeVisible();const layerToggle=page.locator('.map-layers-panel input[type=checkbox]').first();await layerToggle.uncheck();await expect(layerToggle).not.toBeChecked();await layerToggle.check();await page.getByRole('button',{name:'Close map layers'}).click();await page.getByRole('button',{name:'Draw area of interest',exact:true}).click();const map=page.locator('.leaflet-container');await map.click({position:{x:150,y:205}});await map.click({position:{x:270,y:300}});await expect(page.getByRole('heading',{name:'Custom area selected'})).toBeVisible();await page.getByRole('button',{name:'Clear selection',exact:true}).click();await page.getByRole('tab',{name:/Imagery/}).click();await page.getByRole('button',{name:'Compare observation dates',exact:true}).click();await page.waitForURL('**/temporal?scene=*');
 await page.locator('.observation-timeline').getByRole('button',{name:/After event/}).click();await expect(page.locator('.observation-focus .scene-visual')).toHaveAttribute('data-observation','after');await page.locator('.observation-timeline').getByRole('button',{name:/Before event/}).click();await expect(page.locator('.observation-focus .scene-visual')).toHaveAttribute('data-observation','before');await page.getByRole('button',{name:'Swipe compare',exact:true}).click();await page.getByRole('slider',{name:'Before and after image comparison'}).fill('67');await expect(page.getByRole('slider',{name:'Before and after image comparison'})).toHaveValue('67');await page.getByLabel('after observation date',{exact:true}).fill('2025-05-01');await page.getByRole('button',{name:'WHAT CHANGED HERE?',exact:true}).click();await expect(page.locator('.error-banner')).toContainText('Choose dates in order');await page.getByLabel('before observation date',{exact:true}).fill('2025-06-01');await page.getByLabel('during observation date',{exact:true}).fill('2025-06-18');await page.getByLabel('after observation date',{exact:true}).fill('2025-06-25');await go('/map');await go('/temporal');await expect(page.getByLabel('after observation date',{exact:true})).toHaveValue('2025-06-25');console.log('PASS: area selection, timeline imagery, swipe comparison, date validation and persistence');
 await go('/emergency');await runAnalysis();await page.getByRole('button',{name:'Monitor recovery',exact:true}).click();await expect(page.locator('.observation-focus .scene-visual')).toHaveAttribute('data-observation','recovery');await expect(page.getByRole('heading',{name:'Recovery monitoring · prototype observation'})).toBeVisible();await page.getByRole('button',{name:'Generate emergency report',exact:true}).click();await page.waitForURL('**/reports');await expect(page.getByRole('heading',{name:'Emergency Situation Report',exact:true})).toBeVisible();await shot('report-preview',true);await pdfDownload('emergency-report');await page.reload();await expect(page.getByRole('heading',{name:'Emergency Situation Report',exact:true})).toBeVisible();await page.getByRole('button',{name:'All reports',exact:true}).click();await expect(page.locator('.report-card')).toHaveCount(2);await page.locator('.report-card-cover').first().click();await expect(page.getByRole('heading',{name:'Emergency Situation Report',exact:true})).toBeVisible();console.log('PASS: emergency impact, recovery, report preview and PDF export');
 await go('/history');await page.locator('.analysis-title-cell').first().click();await page.waitForURL('**/emergency?analysis=*');await expect(page.locator('.analysis-results')).toBeVisible();await expect(page.getByRole('button',{name:'Generate report',exact:true})).toBeEnabled();console.log('PASS: history reopens a completed analysis without rerunning');
 const email=`orbital-ux-${Date.now()}@example.test`;await go('/register');await shot('register-organization');await page.getByLabel('Organization name',{exact:true}).fill('Coastal Response Agency');await page.getByLabel('Organization type',{exact:true}).selectOption('disaster');await page.locator('.organization-fields input[list]').fill('Kochi, Kerala, India');await page.getByRole('button',{name:'Continue to your account'}).click();await page.getByLabel('Full name',{exact:true}).fill('Jordan Ellis');await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Prototype-Test-Only-2026!');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create account & workspace'}).click();await page.waitForURL('**/organizations');await expect(page.locator('.organization-card').filter({hasText:'Coastal Response Agency'})).toBeVisible();await shot('organizations',true);await page.locator('.organization-card').filter({hasText:'Coastal Response Agency'}).click();await page.waitForURL('**/missions');await page.getByRole('radio',{name:/Flood Analysis/}).click();await page.getByRole('button',{name:'Continue to dashboard'}).click();await page.waitForURL(base+'/');await expect(orgMenu()).toContainText('Coastal Response Agency');await expect(page.locator('.analyses-table')).toHaveCount(0);await go('/map');await page.getByRole('button',{name:'Save location',exact:true}).click();await go('/emergency');await expect(orgMenu()).toContainText('Coastal Response Agency');await runAnalysis();await page.getByRole('button',{name:'Generate emergency report',exact:true}).click();await page.waitForURL('**/reports');await expect(page.locator('.report-metadata')).toContainText('Coastal Response Agency');await pdfDownload('custom-organization-report');console.log('PASS: organization registration, isolated workspace, custom organization analysis and report');
 await go('/organizations');await page.getByRole('button',{name:'Add organization',exact:true}).click();await page.getByRole('dialog').getByLabel('Organization name',{exact:true}).fill('Canopy Watch');await page.getByRole('dialog').getByLabel('Organization type',{exact:true}).selectOption('environment');await page.getByRole('dialog').locator('input[list]').fill('Amazon Basin, Mato Grosso, Brazil');await page.getByRole('button',{name:'Create organization',exact:true}).click();await page.waitForURL('**/missions');await page.getByRole('radio',{name:/Deforestation Analysis/}).click();await page.getByRole('button',{name:'Continue to dashboard'}).click();await page.waitForURL(base+'/');await go('/history');await expect(page.locator('.analyses-table')).toHaveCount(0);await go('/saved');await expect(page.locator('.saved-card')).toHaveCount(0);await go('/reports');await expect(page.locator('.report-card')).toHaveCount(0);await go('/temporal');await runAnalysis(false);await expect(page.locator('.result-change-panel')).toContainText('Deforestation');await chooseOrg('Coastal Response Agency');await expect(page.locator('.sidebar-mission')).toContainText('Flood Analysis');await go('/history');await expect(page.locator('.analyses-table tbody tr')).toHaveCount(1);await go('/saved');await expect(page.locator('.saved-card')).toHaveCount(1);await chooseOrg('Canopy Watch');await expect(page.locator('.sidebar-mission')).toContainText('Deforestation Analysis');await expect(page.locator('.map-location-card')).toContainText('Amazon Basin');console.log('PASS: multiple organization isolation and remembered mission/location');
 await go('/settings');await page.getByRole('switch',{name:'Compact tables'}).click();await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.reload();await expect(page.getByRole('switch',{name:'Compact tables'})).toHaveAttribute('aria-checked','true');await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/login');await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Prototype-Test-Only-2026!');await page.getByRole('button',{name:'Sign in to workspace'}).click();await page.waitForURL('**/organizations');await expect(page.locator('.organization-card').filter({hasText:'Canopy Watch'})).toBeVisible();console.log('PASS: profile/preferences persistence and local sign-in');
 for(const route of ['/','/welcome','/login','/register','/organizations','/missions','/search','/map','/temporal','/emergency','/changes','/reports','/history','/saved','/settings']){await go(route);await expect(page.locator('main')).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);if(overflow>2)throw new Error(`Desktop overflow on ${route}: ${overflow}`);}
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mobilePage=await mobile.newPage();mobilePage.on('pageerror',e=>errors.push(e.message));await mobilePage.goto(base);await mobilePage.waitForTimeout(1000);await mobilePage.screenshot({path:'artifacts/ux/dashboard-mobile.png',fullPage:true});await mobilePage.getByRole('button',{name:'Open navigation'}).click();await expect(mobilePage.locator('.sidebar')).toHaveClass(/sidebar-open/);await mobilePage.locator('.main-nav').getByRole('link',{name:'Reports'}).click();await mobilePage.waitForURL('**/reports');
 for(const route of ['/','/search','/temporal','/emergency','/map','/reports','/history','/saved','/settings','/organizations','/missions','/welcome','/login','/register']){await mobilePage.goto(base+route,{waitUntil:'domcontentloaded'});await mobilePage.waitForTimeout(350);const overflow=await mobilePage.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);if(overflow>2)throw new Error(`Mobile overflow on ${route}: ${overflow}px`);}
 for(const width of [768,1024,1280]){await mobilePage.setViewportSize({width,height:900});for(const route of ['/','/search','/temporal','/map','/organizations','/settings']){await mobilePage.goto(base+route,{waitUntil:'domcontentloaded'});await mobilePage.waitForTimeout(250);const overflow=await mobilePage.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);if(overflow>2)throw new Error(`Responsive overflow ${width}px on ${route}: ${overflow}`);}}
 console.log('PASS: all routes, mobile navigation, and mobile/tablet/desktop widths');
 if(errors.length)throw new Error(`Browser errors: ${[...new Set(errors)].join(' | ')}`);
 console.log('ALL UX REGRESSION TESTS PASSED');
}catch(error){await shot('test-failure',true);console.error(error);process.exitCode=1;}finally{await browser.close();}
